### ISSUE TITLE
Enable storing of secrets into Credential Manager/Keychain

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#10]
The token would be generated by dotnet/diagnostics#1747

**Comment by wiktork** [comment]
The api key no longer needs to be stored, but we may want to store Azure keys into Credential Manager.

**Comment by jander-msft** [comment]
Storage of keys that are provided by the user who configures the .NET Monitor tool is outside of the scope of the tool itself. If there is a compelling scenario by which the .NET Monitor tool should load keys from storage locations outside of what is available at this time, a new issue should be logged to describe it.
