### ISSUE TITLE
TLS in new dotnet-monitor sidecar container

### ISSUE THREAD

**Issue by tatsean** [dotnet/dotnet-monitor#1127]
When i use the latest dotnet-monitor image (mcr.microsoft.com/dotnet/monitor:6.0) in kubernetes deployment yaml file, i hit the following error when the sidecar container is starting. Just wondering why can't the image at least provides the self-signed cert or we have to manually add those in ourselves? 

{"Timestamp":"2021-11-09T11:59:05.6129080Z","EventId":15,"LogLevel":"Error","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Unable to listen to https://\u002B:52323. Dotnet-monitor functionality will be limited.","Exception":"System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date. To generate a developer certificate run \u0027dotnet dev-certs https\u0027. To trust the certificate (Windows and macOS only) run \u0027dotnet dev-certs https --trust\u0027. For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action\u00601 configureOptions)

**Comment by jander-msft** [comment]
You will have to provide your own certificate or remove HTTPS usage (not recommended). The default URLs bind to "any host" in the Docker image, so there is no host which could be specified if we attempted to provide a default certificate.

The certificate is specified via configuring the default certificate via the Kestrel:Certificates:Default key: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#replace-the-default-certificate-from-configuration

**Comment by mleybsage** [comment]
> You will have to provide your own certificate or remove HTTPS usage (not recommended). The default URLs bind to "any host" in the Docker image, so there is no host which could be specified if we attempted to provide a default certificate.
> 
> The certificate is specified via configuring the default certificate via the Kestrel:Certificates:Default key: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#replace-the-default-certificate-from-configuration

I'm attempting to host dotnet-monitor as a sidecar container in an ECS task, which is to listen on a HTTP address internally within the VPC. Could you please provide guidance on how to configure in such a way to remove HTTPS usage?

**Comment by jander-msft** [comment]
> @jander-msft
> 
> > You will have to provide your own certificate or remove HTTPS usage (not recommended). The default URLs bind to "any host" in the Docker image, so there is no host which could be specified if we attempted to provide a default certificate.
> > The certificate is specified via configuring the default certificate via the Kestrel:Certificates:Default key: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#replace-the-default-certificate-from-configuration
> 
> I'm attempting to host dotnet-monitor as a sidecar container in an ECS task, which is to listen on a HTTP address internally within the VPC. Could you please provide guidance on how to configure in such a way to remove HTTPS usage?

You can:
- Specify the URL via the `--urls` command line parameter e.g. `dotnet monitor collect --urls http://localhost:52323`
- Specify any of the following environment variables with the value of the URL: `ASPNETCORE_URLS`, `DOTNETMONITOR_URLS`

**Comment by jander-msft** [comment]
> When i use the latest dotnet-monitor image (mcr.microsoft.com/dotnet/monitor:6.0) in kubernetes deployment yaml file, i hit the following error when the sidecar container is starting. Just wondering why can't the image at least provides the self-signed cert or we have to manually add those in ourselves?

The image cannot provide a self-signed cert because the host name is unknown at the time of creation of the image. The default URL of the dotnet-monitor image is `https://+:52323`
