### ISSUE TITLE
EFK stack integration?

### ISSUE THREAD

**Issue by khteh** [dotnet/dotnet-monitor#1132]
I have been using EFK stack with my ASP.Net applications for years. Does it make sense to integrate this monitoring into this familiar environment?

**Comment by kelltrick** [comment]
Hi @khteh, can describe what info you'd like from `dotnet-monitor` to show up in EFK? `dotnet-monitor` does send it's logs to stdout, which can be picked up by `Fluent-Bit`. And, like most other dotnetcore apps, `dotnet-monitor` can be configured to use JSON logging as well. 

The integration scenario I can think of is the ability to conditionally egress trace data to `Fluent-Bit` via a [collection trigger](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/collectionrules.md) over http using the Fluent built-in HTTP input plugin.

**Comment by khteh** [comment]
Currently I run fluentd as a sidecar in the same statefulset as my dotnet app in K8s. Where would the dotnet-monitor run in this case?

**Comment by jander-msft** [comment]
A prebuilt `dotnet monitor` image is available to run as a sidecar in multi-container environments: https://hub.docker.com/_/microsoft-dotnet-monitor

See the documentation at https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md for an example of how to configure it to be able to diagnose applications in other containers within the same pod.
