### ISSUE TITLE
Running locally just returns 404 responses

### ISSUE THREAD

**Issue by martinmine** [dotnet/dotnet-monitor#1139]
### Description

I am trying to set up `dotnet monitor` locally on my own machine according to what is documented on the announcement post for `dotnet monitor` in .NET 6 [here](https://devblogs.microsoft.com/dotnet/announcing-dotnet-monitor-in-net-6/). I have a dead simple ASP.NET Core 6 app that I wanna debug for demo purposes.
I have installed the tool using `dotnet tool install -g dotnet-monitor`, and I start it by running `dotnet monitor collect`. In the output from the application, I can see that the process has started up an HTTP and HTTPS endpoint. However, when I send an HTTP GET request to `http://localhost:52325/processes` it just gives me 404 responses.

I am having a really hard time figuring out how to use this tool as I do not know if this is a configuration error from my side or there is something wrong with the tool itself (which I doubt). The link to "Running on local machine" [under the documentations folder](https://github.com/dotnet/dotnet-monitor/tree/main/documentation#) doesn't lead anywhere and I feel really lost understanding how to set this up. 

### Other information
When I run `dotnet monitor collect` this is the output:
```
13:12:40 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The Subject field is required.
13:12:40 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The PublicKey field is required.
13:12:40 warn: Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver[21]
      MonitorApiKey settings are invalid: The configuration parameter PublicKey must be base64Url encoded, the value '' could not be parsed as a base64Url-encoded string.
13:12:40 warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'https://localhost:52323'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
13:12:40 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:52323
13:12:40 info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:52325
13:12:40 info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
13:12:40 info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
13:12:40 info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\marti\.dotnet\tools\.store\dotnet-monitor\6.0.0\dotnet-monitor\6.0.0\tools\net6.0\any\
```

**Comment by martinmine** [comment]
It turns out that in my case, I had to go towards the HTTPS endpoint and use an auth key as described [here](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/authentication.md). It would be very nice if this would be documented clearly some place which endpoints are available under HTTP or HTTPS, and then link to the authentication documentation page. A getting started page which clarified all of these cases would be super helpful for others!

**Comment by darraghjones** [comment]
just spent almost on hour on this. why does the application listen on http (port 52325) if it's just going to return 404? to make it more confusing the / path acturally returns the openapi json....just none of the paths defined there work. 

i can't even find this behaviour documented anywhere...and believe me i've looked.

**Comment by luizhpriotto** [comment]
In my case, the issue (404) was caused by authentication. When I set the option

```
collect
  - --no-auth
```
it worked normally.
