### ISSUE TITLE
ARM Docker Images

### ISSUE THREAD

**Issue by LiamMorrow** [dotnet/dotnet-monitor#1141]
## Background and Motivation

I run a K8s cluster on a bunch of raspberry pi 4's, and it is really useful to have base dotnet runtime images that target arm64.

## Proposed Feature

It'd be good if there was preprepared docker images published targeting ARM64 to help with simplicity of setting up monitor.

**Comment by jander-msft** [comment]
Thanks for the suggestion! I wanted to let you know that starting with 7.0 Preview 3 (released image) and 6.2 Alpha 1 (nightly image), we have ARM64v8 images available in preview. These images have a `-arm64v8` suffix on the end of their tags.

Here's the tag list for the released images (mcr.microsoft.com/dotnet/monitor): https://mcr.microsoft.com/v2/dotnet/monitor/tags/list
Here's the tag list for the nightly images (mcr.microsoft.com/dotnet/nightly/monitor): https://mcr.microsoft.com/v2/dotnet/nightly/monitor/tags/list
