### ISSUE TITLE
Metrics created with  System.Diagnostics.Metrics not available in dotnet-monitor

### ISSUE THREAD

**Issue by piotrekmich79** [dotnet/dotnet-monitor#1144]
### Description

I've created metrics with a new api (https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation). Metrics works fine, they are presented by dotnet-counter, but they are not available in \metrics endpoint in dotnet-monitor. 
My sample application exposes two kind of metrics:
- SampleWebApi.MetricsProvider using EventCounters api - those metrics are available in dotnet-counter and dotnet-monitor
- SampleWebApi.DiagnosticSourceMetricProvider using new System.Diagnostics.Metrics api - those metrics are available only in dotnet-counter; the implementation is a copy of an example (https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation)

Checked on linux and windows.

### Configuration

dotnet-monitor configuration file i've used:

    "Metrics": {
        "Enabled": "True",
        "Endpoints": http://*:9090,
        "IncludeDefaultProviders": "True",
        "Providers": [
            {
                "ProviderName": "SampleWebApi.MetricsProvider"
            },
            {
                "ProviderName": "SampleWebApi.DiagnosticSourceMetricProvider"              
            }
        ]
    }

**Comment by jander-msft** [comment]
System.Diagnostics.Metrics support has not been adde yet. See #329
