### ISSUE TITLE
Environment variables example in configuration.md is misleading

### ISSUE THREAD

**Issue by mleybsage** [dotnet/dotnet-monitor#1147]
### Documentation Request

Line in file configuration.md reads:

"The same configuration can be expressed via environment variables using the DotnetMonitor_ prefix and using __(double underscore) as the hierarchical separator"

Yet example shows:

```
export Authentication__MonitorApiKey__Subject="ae5473b6-8dad-498d-b915-ffffffffffff"
export Authentication__MonitorApiKey__PublicKey="eyffffffffffffFsRGF0YSI6e30sIkNydiI6IlAtMzg0IiwiS2V5T3BzIjpbXSwiS3R5IjoiRUMiLCJYIjoiTnhIRnhVZ19QM1dhVUZWVzk0U3dUY3FzVk5zNlFLYjZxc3AzNzVTRmJfQ3QyZHdpN0RWRl8tUTVheERtYlJuWSIsIlg1YyI6W10sIlkiOiJmMXBDdmNoUkVpTWEtc1h6SlZQaS02YmViMHdrZmxfdUZBN0Vka2dwcjF5N251Wmk2cy1NcHl5RzhKdVFSNWZOIiwiS2V5U2l6ZSI6Mzg0LCJIYXNQcml2YXRlS2V5IjpmYWxzZSwiQ3J5cHRvUHJvdmlkZXJGYWN0b3J5Ijp7IkNyeXB0b1Byb3ZpZGVyQ2FjaGUiOnt9LCJDYWNoZVNpZ25hdHVyZVByb3ZpZGVycyI6dHJ1ZSwiU2lnbmF0dXJlUHJvdmlkZXJPYmplY3RQb29sQ2FjaGffffffffffff19"
```

The DotnetMonitor_ prefix is missing on these names. Is this correct?

**Comment by jander-msft** [comment]
The `DotnetMonitor_` prefix is optional in a sense. An environment variable named `X` will map to the same configuration section as a variable named `DotnetMonitor_X`, however the latter will have a higher precedence.
