### ISSUE TITLE
Is any Grafana dashboard created for the default dotnet metrics? 

### ISSUE THREAD

**Issue by jaya-rama** [dotnet/dotnet-monitor#1161]
Hi 

I have pushed dotnet monitor metrics to prometheus now I need to create a grafana dashboard is there any dashboard that the team created?

**Comment by poppastring** [comment]
Hey @jaya-rama 

Developers in the .NET community have documented this scenario already! Check out this great [blog post on Configuring dotnet-monitor with Prometheus and Grafana](https://dotnetos.org/blog/2021-11-22-dotnet-monitor-grafana/). 

Hope this helps!

**Comment by jaya-rama** [comment]
> Hey @jaya-rama
> 
> Developers in the .NET community have documented this scenario already! Check out this great [blog post on Configuring dotnet-monitor with Prometheus and Grafana](https://dotnetos.org/blog/2021-11-22-dotnet-monitor-grafana/).
> 
> Hope this helps!

Thanks

**Comment by hueifeng** [comment]
I created a dashboard https://github.com/hueifeng/dotnet-monitor-on-k8s
