### ISSUE TITLE
Kubernetes deployment example

### ISSUE THREAD

**Issue by trhumphries** [dotnet/dotnet-monitor#1200]
### Documentation Request
I'd like to see specific examples of the resource definitions that should be used to deploy this as a sidecar in Kubernetes

**Comment by jander-msft** [comment]
I've added an example deployment of the `dotnet monitor` image in Kubenetes that points out the unique aspects of how the tool was configured. Please let us know if there is any additional information you think would be beneficial for getting started in Kubernetes (note that we will likely not document Kubernetes concepts themselves unless it has some specific impact on configuring the `dotnet monitor` image).
