### ISSUE TITLE
Empty list of processes in AWS ECS

### ISSUE THREAD

**Issue by tylerohlsen** [dotnet/dotnet-monitor#1207]
I'm running into a very similar issue to [Issue 411](https://github.com/dotnet/dotnet-monitor/issues/411).  I created dotnet-monitor as a sidecar container in AWS ECS and the `/processes` endpoint is not finding my service's dotnet process, it returns an empty array result `[]`.  

I set the log level to `Debug` via environment variables and that did not give any more information:  
```shell
DotnetMonitor_Logging__LogLevel__Default="Debug"
DotnetMonitor_Logging__LogLevel__Microsoft="Debug"
DotnetMonitor_Logging__LogLevel__Microsoft.Diagnostics="Debug"
DotnetMonitor_Logging__LogLevel__Microsoft.Hosting.Lifetime="Debug"
```
produced logs:
```json
{"Timestamp":"2021-12-14T18:27:10.3605265Z","EventId":1,"LogLevel":"Debug","Category":"Microsoft.Extensions.Hosting.Internal.Host","Message":"Hosting starting","State":{"Message":"Hosting starting","{OriginalFormat}":"Hosting starting"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:11.6588063Z","EventId":15,"LogLevel":"Error","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Unable to listen to https://\u002B:52323. Dotnet-monitor functionality will be limited.","Exception":"System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date. To generate a developer certificate run \u0027dotnet dev-certs https\u0027. To trust the certificate (Windows and macOS only) run \u0027dotnet dev-certs https --trust\u0027. For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054. at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action\u00601 configureOptions) at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions) at Microsoft.Diagnostics.Tools.Monitor.AddressListenResults.\u003C\u003Ec__DisplayClass10_0.\u003CListen\u003Eb__0(ListenOptions listenOptions) in /_/src/Tools/dotnet-monitor/AddressListenResults.cs:line 87 at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.ListenAnyIP(Int32 port, Action\u00601 configure) at Microsoft.Diagnostics.Tools.Monitor.AddressListenResults.Listen(KestrelServerOptions options, String url) in /_/src/Tools/dotnet-monitor/AddressListenResults.cs:line 103","State":{"Message":"Unable to listen to https://\u002B:52323. Dotnet-monitor functionality will be limited.","url":"https://\u002B:52323","{OriginalFormat}":"Unable to listen to {url}. Dotnet-monitor functionality will be limited."},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:11.7664226Z","EventId":25,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Tools.Monitor.MonitorApiKeyConfigurationObserver","Message":"MonitorApiKey settings have changed. The new settings have passed validation.","State":{"Message":"MonitorApiKey settings have changed. The new settings have passed validation.","apiAuthenticationConfigKey":"MonitorApiKey","{OriginalFormat}":"{apiAuthenticationConfigKey} settings have changed. The new settings have passed validation."},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:11.7844777Z","EventId":13,"LogLevel":"Warning","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.","State":{"Message":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.","{OriginalFormat}":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments."},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:12.7802764Z","EventId":0,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Overriding address(es) \u0027https://\u002B:52323, http://*:52323\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.","State":{"Message":"Overriding address(es) \u0027https://\u002B:52323, http://*:52323\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.","addresses":"https://\u002B:52323, http://*:52323","{OriginalFormat}":"Overriding address(es) \u0027{addresses}\u0027. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead."},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:12.9718956Z","EventId":14,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://[::]:52323","State":{"Message":"Now listening on: http://[::]:52323","address":"http://[::]:52323","{OriginalFormat}":"Now listening on: {address}"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:12.9798279Z","EventId":14,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://[::]:52325","State":{"Message":"Now listening on: http://[::]:52325","address":"http://[::]:52325","{OriginalFormat}":"Now listening on: {address}"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:13.0597380Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Content root path: /app/.store/dotnet-monitor/6.0.0/dotnet-monitor/6.0.0/tools/net6.0/any/","State":{"Message":"Content root path: /app/.store/dotnet-monitor/6.0.0/dotnet-monitor/6.0.0/tools/net6.0/any/","contentRoot":"/app/.store/dotnet-monitor/6.0.0/dotnet-monitor/6.0.0/tools/net6.0/any/","{OriginalFormat}":"Content root path: {contentRoot}"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:13.0595678Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Hosting environment: Production","State":{"Message":"Hosting environment: Production","envName":"Production","{OriginalFormat}":"Hosting environment: {envName}"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:13.0593803Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Application started. Press Ctrl\u002BC to shut down.","State":{"Message":"Application started. Press Ctrl\u002BC to shut down.","{OriginalFormat}":"Application started. Press Ctrl\u002BC to shut down."},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:13.0591210Z","EventId":17,"LogLevel":"Debug","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Bound metrics address: http://[::]:52325","State":{"Message":"Bound metrics address: http://[::]:52325","address":"http://[::]:52325","{OriginalFormat}":"Bound metrics address: {address}"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:12.9823501Z","EventId":16,"LogLevel":"Debug","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Bound default address: http://[::]:52323","State":{"Message":"Bound default address: http://[::]:52323","address":"http://[::]:52323","{OriginalFormat}":"Bound default address: {address}"},"Scopes":[]},
{"Timestamp":"2021-12-14T18:27:13.0600299Z","EventId":2,"LogLevel":"Debug","Category":"Microsoft.Extensions.Hosting.Internal.Host","Message":"Hosting started","State":{"Message":"Hosting started","{OriginalFormat}":"Hosting started"},"Scopes":[]},
```

So I exec'd into the _dotnet-monitor_ container and ran `ps aux` with this result:  
```plaintext
PID   USER     TIME  COMMAND
    1 root      0:03 dotnet-monitor collect --urls https://+:52323 --metricUrls http://+:52325 --urls http://*:52323 --no-auth
    7 root      0:00 /managed-agents/execute-command/amazon-ssm-agent
   22 root      0:00 /managed-agents/execute-command/ssm-agent-worker
  195 root      0:00 /managed-agents/execute-command/ssm-session-worker ecs-execute-command-0ce07dccfc8ce1e4d bdd0676ca34d44f7a0b3c531938a5625-1453563508
  207 root      0:00 /bin/sh
  208 root      0:00 ps aux
```
So it truly does not see the process of the main service container.  So I tried setting _dotnet-monitor_ in listen mode with these environment variables:
```shell
DotnetMonitor_DiagnosticPort__ConnectionMode="Listen"
DotnetMonitor_DiagnosticPort__EndpointName="\\.\pipe\dotnet-monitor-pipe"
```
and on the main service container:
```shell
DOTNET_DiagnosticPorts="dotnet-monitor-pipe,suspend"
```
but the service never starts up and is blocked with this message:
```shell
The runtime has been configured to pause during startup and is awaiting a Diagnostics IPC ResumeStartup command from a Diagnostic Port.
DOTNET_DiagnosticPorts="dotnet-monitor-pipe,suspend"
DOTNET_DefaultDiagnosticPortSuspend=0
```
I'm not finding information on if named pipes should work across containers in the same AWS ECS Task.  

Note that all of these approaches work for me on Windows.

**Comment by tylerohlsen** [comment]
My fallback plan is to install `dotnet-monitor` as a global tool inside our service container, but I was hoping to avoid that and use it as a sidecar.  Anyone else gotten this to work in ECS?

**Comment by jander-msft** [comment]
Assuming your `dotnet monitor` container is a Linux container (because you show that you exec'd into it and ran `ps`), it is using Unix Domain Sockets for discovering and communicating with other .NET processes. This requires either that:
- in connect mode (the default mode of `dotnet monitor`) to have a shared volume that is mounted as the `/tmp` directory in the `dotnet monitor` container and any target containers you wish to monitor.
- in listen mode to have the environment variables that you set AND to have the directory in which the Unix Domain Socket file is mounted among the `dotnet monitor` container and the target containers you wish to monitor. For example, if your diagnostic port is established at `/diag/port`, then a shared volume needs to be mounted at `/diag` in the `dotnet monitor` container and (if using the same path) mounted at `/diag` in each target container.

Listen mode is the recommended configuration when working in multi-container environments.

We'll update the documentation to show a minimal example Kubernetes deployment to help get users a starting point.

**Comment by tylerohlsen** [comment]
Thanks for the quick reply @jander-msft!  Creating _bind mounts_ (as AWS ECS likes to call them) on the two containers seems to sometime fix it.  It looks like it is still intermittently returning an empty array.  I'll wait a bit longer to see if it just takes some time for it to discover the other process.

**Comment by tylerohlsen** [comment]
Waiting longer didn't help.  Killing and re-creating the containers does randomly get them to respond correctly with no change to the container definitions.  I also tried setting a `dependsOn` with status `HEALTHY` to force the service to start first (and the other direction) and that didn't help.  It still randomly does and does not work when in "Connect" mode.

**Comment by tylerohlsen** [comment]
I had some trouble switching to "Listen" mode, but now that I have switched it very consistently is able to list the process!  I used the dotnet diagnostics [documentation](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#diagnostic-ports) to come up with the correct format of the Unix Domain Sockets in the environment variables.  So for completeness, here's my environment variables that got it all to work:

dotnet-monitor container:  
```shell
# Note the single underscore after DotnetMonitor and double underscore otherwise - that threw me off for a while
DotnetMonitor_DiagnosticPort__ConnectionMode="Listen"
DotnetMonitor_DiagnosticPort__EndpointName="/tmp/dotnet-monitor-pipe"
DotnetMonitor_DefaultProcess__Filters__0__Key="ProcessName"
DotnetMonitor_DefaultProcess__Filters__0__Value="dotnet"
```

my service container:  
```shell
DOTNET_DiagnosticPorts="/tmp/dotnet-monitor-pipe,nosuspend,connect"
```

And as mentioned before, I set up an ECS _bind mount_ in both containers that map to container path `/tmp`

**Comment by maciejsobocinski** [comment]
> Assuming your `dotnet monitor` container is a Linux container (because you show that you exec'd into it and ran `ps`), it is using Unix Domain Sockets for discovering and communicating with other .NET processes. This requires either that:
> 
> * in connect mode (the default mode of `dotnet monitor`) to have a shared volume that is mounted as the `/tmp` directory in the `dotnet monitor` container and any target containers you wish to monitor.
> * in listen mode to have the environment variables that you set AND to have the directory in which the Unix Domain Socket file is mounted among the `dotnet monitor` container and the target containers you wish to monitor. For example, if your diagnostic port is established at `/diag/port`, then a shared volume needs to be mounted at `/diag` in the `dotnet monitor` container and (if using the same path) mounted at `/diag` in each target container.
> 
> Listen mode is the recommended configuration when working in multi-container environments.
> 
> We'll update the documentation to show a minimal example Kubernetes deployment to help get users a starting point.

Hi - just curious...why is Listen mode the recommended config for multi-container?

I'm in a similar scenario running on AWS Fargate with dotnet-monitor as a side car.  "Connect" mode seems to work fine after mounting /tmp as a shared volume. I'm having trouble getting "Listen" mode working though - after fiddling with it for a while the problem seems to be that my app runs as non-root then shared volume has rwx for everybody but then the unix socket that dotnet-monitor creates inside the shared volume does not have write for non-root which causes my app to hang waiting to get a connection...if I remote into the container and manually give the socket write for everybody it starts working. Any ideas on how I could get this working ?

**Comment by jander-msft** [comment]
> Hi - just curious...why is Listen mode the recommended config for multi-container?

If there is more than one application container that the single `dotnet monitor` instance is observering, and the entrypoint process for two or more of those containers is dotnet, then those processes will likely have the same process ID. The tool will only observe those as a single process when running in `connect` mode.

> I'm in a similar scenario running on AWS Fargate with dotnet-monitor as a side car. "Connect" mode seems to work fine after mounting /tmp as a shared volume. I'm having trouble getting "Listen" mode working though - after fiddling with it for a while the problem seems to be that my app runs as non-root then shared volume has rwx for everybody but then the unix socket that dotnet-monitor creates inside the shared volume does not have write for non-root which causes my app to hang waiting to get a connection...if I remote into the container and manually give the socket write for everybody it starts working. Any ideas on how I could get this working ?

Running the `dotnet monitor` container as the same user as the applications is the easiest way to allow the application containers to be able to connect to the tool's socket.

**Comment by maciejsobocinski** [comment]
> > Hi - just curious...why is Listen mode the recommended config for multi-container?
> 
> If there is more than one application container that the single `dotnet monitor` instance is observering, and the entrypoint process for two or more of those containers is dotnet, then those processes will likely have the same process ID. The tool will only observe those as a single process when running in `connect` mode.
> 
> > I'm in a similar scenario running on AWS Fargate with dotnet-monitor as a side car. "Connect" mode seems to work fine after mounting /tmp as a shared volume. I'm having trouble getting "Listen" mode working though - after fiddling with it for a while the problem seems to be that my app runs as non-root then shared volume has rwx for everybody but then the unix socket that dotnet-monitor creates inside the shared volume does not have write for non-root which causes my app to hang waiting to get a connection...if I remote into the container and manually give the socket write for everybody it starts working. Any ideas on how I could get this working ?
> 
> Running the `dotnet monitor` container as the same user as the applications is the easiest way to allow the application containers to be able to connect to the tool's socket.

Thank you for the quick response! That makes sense to me. 

In our case then I think it makes sense to go with Connect mode - dotnet would be monitoring only one process in a single container (which are then replicated across multiple "ECS Tasks" behind a load balancer with each task being one container+side car dotnet monitor dedicated to it). Just a bit simpler for us to pull the image as is from mcr vs having to build one on top of it to add the shared non root user.

**Comment by maciejsobocinski** [comment]
> Waiting longer didn't help. Killing and re-creating the containers does randomly get them to respond correctly with no change to the container definitions. I also tried setting a `dependsOn` with status `HEALTHY` to force the service to start first (and the other direction) and that didn't help. It still randomly does and does not work when in "Connect" mode.

For reference I am experiencing the exact same issue in "CONNECT" mode on ECS Fargate. Tried DependsOn as well to launch my app container before the dotnet-container....works sometimes sometimes it does not. It seems like a timing issue where my application container starts but the actual app itself hasn't fully come online, ECS then (since first container started successfully) launches the dotnet-monitor container which ends up starting up before my application and going forward any requests to dotnet-monitor get "System.ArgumentException: Unable to discover a target process." . I have an ECS Service running with multiple load balanced tasks (each with my app + dotnet-monitor sidecar) and upon deployment some tasks work fine others get the exception.

**Comment by maciejsobocinski** [comment]
I also tried overwriting the ENTRYPOINT for dotnet-monitor to "sleep 60 && dotnet-monitor collect --urls https://+:52323" that sleeps long enough for my app to start and successfully get hit with a health check before dotnet-monitor starts up .... didn't help still getting  "System.ArgumentException: Unable to discover a target process." about 1/2 the time in "CONNECT" mode :-/ ...time to cave in and switch to LISTEN mode
