### ISSUE TITLE
How to use .NET monitor docker?

### ISSUE THREAD

**Issue by Oleg26Dev** [dotnet/dotnet-monitor#1246]
I have run the docker
>docker run -it --rm mcr.microsoft.com/dotnet/monitor:latest

Then run a browser with query
https://localhost:52323/processes
or simply
https://localhost:52323

but no any responses.
I run in PS
PS D:\> Invoke-RestMethod http://localhost:52323/logs
Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Invoke-RestMethod http://localhost:52323/logs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

What is incorrect?

**Comment by jander-msft** [comment]
The routes under the address with the 52323 port are authenticated, which is why you are receiving a HTTP 401. See https://github.com/dotnet/dotnet-monitor/blob/main/documentation/authentication.md for documentation on how to configure authentication.

**Comment by jander-msft** [comment]
Please let us know if you need further help with this issue.
