### ISSUE TITLE
Logging source generator

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-monitor#1258]
Similar to https://github.com/dotnet/dotnet-monitor/issues/1115, the logging source generator is available since .NET 6

**Comment by jander-msft** [comment]
Thanks for the suggestion! The [logging source generator](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator) requires that the message is a constant string. In dotnet-monitor, however, all of the logging messages are loaded from a resources. Thus, unfortunately, the logging source generator cannot be used in dotnet-monitor.
