### ISSUE TITLE
Investigate: Does schema.json need a "$schema" property?

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#127]
In VS Code, the following warning is shown when using the schema in the settings.json file:
![schema](https://user-images.githubusercontent.com/17344677/113441239-ce4bef00-93a2-11eb-85bd-1cbfa23198dd.png)

This is a benign error and the IntelliSense seems to work.

Should we add a "$schema" property to the schema to avoid the error? Does leaving a "$schema" property in the settings.json file cause issues with the configuration system consuming the settings.json file (if it does, then maybe we don't want to add "$schema" to the schema)?

cc @wiktork, @shirhatti

**Comment by wiktork** [comment]
I believe this is by design. See https://code.visualstudio.com/Docs/languages/json#_mapping-in-the-json

**Comment by jander-msft** [comment]
JSON Schema has $schema as a property of their self-describing schema: https://json-schema.org/draft/2020-12/meta/core

https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.8.1.1 also says that "The "$schema" keyword SHOULD be used in the document root schema object"

**Comment by jander-msft** [comment]
> I believe this is by design. See https://code.visualstudio.com/Docs/languages/json#_mapping-in-the-json

So then would our recommendation be this? https://code.visualstudio.com/Docs/languages/json#_mapping-in-the-user-settings

**Comment by jander-msft** [comment]
I think we should add it to the schema so long as it doesn't mess with the configuration system. I assume that the JSON deserialization is smart enough to know that $schema is not actually part of the objects.

**Comment by wiktork** [comment]
Based on another discussion, we likely want the user to freely merge other configuration into this file anyway, so I am relaxing the schema to allow other properties.
