### ISSUE TITLE
High CPU usage for process 'dotnet-moni+' when running in Azure Web App (Linux)

### ISSUE THREAD

**Issue by CodeMatt17** [dotnet/dotnet-monitor#1326]
We are experiencing high CPU usage from the process 'dotnet-moni+' when running in Azure Web App (Linux) affecting the performance of our API in Production. The API we have in Production has about 900,000 requests a day so does have a decent amount of traffic. When we do see this high CPU usage pop up we restart the web app and it goes back to normal for a few weeks but after a few weeks later we get the same issue of high CPU from that same process again so it seems cumulative. Has anyone experienced this issue?

See the screenshot below taken from the Azure diagnostic tools. We run the API on the plan P1v2 with 5 instances. You can see all 5 instances of our API has high CPU usage of that same process.
![HighCpuUsage](https://user-images.githubusercontent.com/18252830/149718260-7b5b6221-d088-46fe-8b82-5d6e3ebbd267.png)

**Comment by kelltrick** [comment]
Hi @CodeMatt17, can you contact me at `pafenelo@microsoft.com`? I need some additional info to investigate this issue.

**Comment by CodeMatt17** [comment]
@kelltrick Thanks, sent you an email.
