### ISSUE TITLE
Querying for trigger state

### ISSUE THREAD

**Issue by poppastring** [dotnet/dotnet-monitor#1539]
Once a trigger is set it would be really helpful to be able to query the state of the trigger to determine if it has fired, or how many more times it potentially could fire. Depending on the output of the trigger (does not have to be a diagnostics file) it may not always be obvious whether a trigger has fired or not. 

A new API could simply output a response describing the basic state of each of the defined triggers.

**Comment by wiktork** [comment]
Do we also want to add enable/disable/reset state for each trigger?
