### ISSUE TITLE
Add Enabled Field To Collection Rules

### ISSUE THREAD

**Issue by kkeirstead** [dotnet/dotnet-monitor#1542]
Adding a "default-true" `Enabled` field to collection rules would make the process of experimenting with different things simpler, especially given the inability to comment out config in JSON. Instead of needing to copy-paste configuration to temporary locations or rewrite it in the future, you'd be able to set `Enabled` to false for a collection rule you'd like to be inactive. This concept could also be applied on a broader scale to other pieces of configuration.

**Comment by jander-msft** [comment]
> especially given the inability to comment out config in JSON.

That's not correct. I use comments in the settings.json file all of the time to block out parts that I don't want to include temporarily.

**Comment by kkeirstead** [comment]
Discussed this offline - seems like the feature is redundant (given that you can comment in JSON). Will close this.
