### ISSUE TITLE
Blob Egress should also have a queue option

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#163]
When egressing to blob storage, we should also allow egress to a queue for better integration with Azure based workflows such as web jobs or azure functions. Detection of blobs alone is very slow.

**Comment by jander-msft** [comment]
Is this suggestion that an artifact should be egressed to a queue or that it is still egressed to a blob and some small message is pushed to a queue that has information about the blob identifier?

**Comment by wiktork** [comment]
> Is this suggestion that an artifact should be egressed to a queue or that it is still egressed to a blob and some small message is pushed to a queue that has information about the blob identifier?

My suggestion was that a small message is also pushed into the queue, to indicate that a blob was uploaded. I didn't consider uploading to the queue directly, I think our artifact sizes are too large.
