### ISSUE TITLE
Allow reading multiple key-per-file locations

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#164]
Currently we only read key-per-file configuration from /etc/dotnet-monitor. However, if the user wants to mount both secrets and config maps, they conflict. The user is forced to use environment variables or settings.json. We should at least allow for 2 locations, or subfolders.

**Comment by jander-msft** [comment]
> However, if the user wants to mount both secrets and config maps, they conflict.

This can be done by using a projected volume: https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/#configure-a-projected-volume-for-a-pod

**Comment by wiktork** [comment]
That worked, thanks!
