### ISSUE TITLE
dotnet-monitor should return more info for processes

### ISSUE THREAD

**Issue by alefranz** [dotnet/dotnet-monitor#19]
Currently `dotnet-monitor` for `/processes` only returns the pid of the process.

I get that this has been mainly deisgned for containers scenarios when you have a single process with pid one, however given it supports more then one process, I think it should return more info to be able to identify the process you are interested to get info from.

Something like the `ps` command in the other tools would be great:
- pid
- process name
- full exe path

https://github.com/dotnet/diagnostics/blob/05a3ae6f69e5dbb405079abeda88e0abec1328b6/src/Tools/Common/Commands/ProcessStatus.cs#L48

**Comment by jander-msft** [comment]
Support for additional process information was added in https://github.com/dotnet/diagnostics/pull/1596

These are current process information routes:
- /processes - Lists discovered processes
- /processes/{id} - Scalar information about the specified process such as process id, runtime instance cookie, name, command line, architecture, and operating system. Some information such as the architecture and operation system may not be known for .NET Core 3.1 processes.
- /processes/{id}/env - The environment block for the specified process. This route only works for .NET 5 and later processes.
