### ISSUE TITLE
Add option to disable HTTP Response egress

### ISSUE THREAD

**Issue by shirhatti** [dotnet/dotnet-monitor#202]
Users of dotnet-monitor may want to disable HTTP Response egress of diagnostic artifacts and only allow other egress providers to be used. Can be used to prevent accidental disclosure of sensitive information

**Comment by wiktork** [comment]
Do this alongside  #9

**Comment by kkeirstead** [comment]
I'm sure there's a simple answer to this question, but should this only pertain to operations that allow for an egress provider parameter? E.g. if the user prints process info using HTTP Response egress, should that also be disabled, or should this only apply to logs, dumps, and traces?
