### ISSUE TITLE
MetricCount does not retain historical values but duplicates current

### ISSUE THREAD

**Issue by RomanBats** [dotnet/dotnet-monitor#2021]
### Description
I have configured the monitor to have MetricCount - '6' and collect them with IntervalSeconds - '10', but it appears that when I call '_/metrics_' it returns me 6 similar values, for example:

![image](https://user-images.githubusercontent.com/5024978/175029343-19961ea0-ace2-4fad-887c-41024b0071fe.png)

And when I refresh the page every 10 seconds - all 6 values are changed, with no regard to the previous values.

### Configuration

**image**: mcr.microsoft.com/dotnet/monitor:6.2-alpine
**target api**: aspnet core 3.1

**Comment by RomanBats** [comment]
Hey @wiktork!
Is it possible, that [WriteMetricDetails ](https://github.com/dotnet/dotnet-monitor/blob/5a3d16515943c87b4d5f66d4289c1826e980d24d/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs#L115) method in [MetricsStore.cs](https://github.com/dotnet/dotnet-monitor/blob/main/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/MetricsStore.cs) uses wrong variable for actual value?

```csharp
        private static async Task WriteMetricDetails(
                    StreamWriter writer,
                    ICounterPayload metric,
                    string metricName,
                    string metricValue)
        {
            await writer.WriteAsync(metricName);
            await writer.WriteLineAsync(FormattableString.Invariant($" {metricValue} {new DateTimeOffset(metric.Timestamp).ToUnixTimeMilliseconds()}"));
        }
```
It should be 
```csharp
$" {metric.Value} {new DateTimeOffset(metric.Timestamp).ToUnixTimeMilliseconds()}"));
```
Becouse "metricValue" is evaluated and assigned once per the whole metricGroup.

**Comment by xsoheilalizadeh** [comment]
I'm not sure if this issue is fixed, I still get duplicated metrics

![image](https://user-images.githubusercontent.com/22220356/190385817-31123d2f-ecfa-4dd4-8eb3-a9a54a4d570f.png)


version: 6.2.2+8abeb94c15ee4175d7078a3f768ed1ef15032bd8"

@jander-msft

**Comment by xsoheilalizadeh** [comment]
Could we reopen this issue or I should create a new issue for it?

**Comment by RomanBats** [comment]
@xsoheilalizadeh, I am using mcr.microsoft.com/dotnet/monitor:6.2.2-alpine
And it works for me:
![image](https://user-images.githubusercontent.com/5024978/191035656-27591ec2-135d-47dd-84a7-5f964fa61b57.png)

**Comment by xsoheilalizadeh** [comment]
@RomanBats I see in your example that you also have `systemruntime_alloc_rate_bytes` several times, maybe I'm missing something here, why there is more than one?

```
# HELP microsoftaspnetcorehosting_requests_per_second Request Rate
# TYPE microsoftaspnetcorehosting_requests_per_second gauge
microsoftaspnetcorehosting_requests_per_second 834 1663597877575
microsoftaspnetcorehosting_requests_per_second 801 1663597882575
microsoftaspnetcorehosting_requests_per_second 754 1663597887575
# HELP microsoftaspnetcorehosting_total_requests Total Requests
# TYPE microsoftaspnetcorehosting_total_requests gauge
microsoftaspnetcorehosting_total_requests 5857 1663597877575
microsoftaspnetcorehosting_total_requests 6658 1663597882575
microsoftaspnetcorehosting_total_requests 7412 1663597887575
```

**Comment by jander-msft** [comment]
> @RomanBats I see in your example that you also have `systemruntime_alloc_rate_bytes` several times, maybe I'm missing something here, why there is more than one?
> 
> 
> 
> ```
> 
> # HELP microsoftaspnetcorehosting_requests_per_second Request Rate
> 
> # TYPE microsoftaspnetcorehosting_requests_per_second gauge
> 
> microsoftaspnetcorehosting_requests_per_second 834 1663597877575
> 
> microsoftaspnetcorehosting_requests_per_second 801 1663597882575
> 
> microsoftaspnetcorehosting_requests_per_second 754 1663597887575
> 
> # HELP microsoftaspnetcorehosting_total_requests Total Requests
> 
> # TYPE microsoftaspnetcorehosting_total_requests gauge
> 
> microsoftaspnetcorehosting_total_requests 5857 1663597877575
> 
> microsoftaspnetcorehosting_total_requests 6658 1663597882575
> 
> microsoftaspnetcorehosting_total_requests 7412 1663597887575
> 
> ```

That's by design. Note that the time stamp for each of those entries is ~5000 ms apart. Prometheus requires a backlog of entries whose sampling interval is smaller than the polling interval of the scraper so that the data can be consistently overlapped over polling samples. The defaults in `dotnet-monitor` are that sampling interval is 5 sec with a backlog of 3 entries per metric

**Comment by xsoheilalizadeh** [comment]
I'm getting strange numbers for one of my metrics which is `microsoftaspnetcorehosting_requests_per_second`.

I'm running a load test with k6 which tells me the rps is ~50, meanwhile, I see different numbers in my metrics.

When I'm using the default configuration with 15s scrape as recommended in docs, I get the following result.

RPS: 840

![image](https://user-images.githubusercontent.com/22220356/191496544-1f8c6653-1548-4b3b-be30-1700f9666454.png)


And when I'm using the following config with 60s scrape I get higher numbers:

```yaml
    - name: DOTNETMONITOR_GlobalCounter__IntervalSeconds 
      value: "10"
    - name: DOTNETMONITOR_Metrics__MetricCount 
      value: "6"
```

RPS: 1514

![image](https://user-images.githubusercontent.com/22220356/191502173-ae9806be-5873-4a02-acfe-45e61b24293b.png)


This is my Prometheus query in grafana:
![image](https://user-images.githubusercontent.com/22220356/191503218-b8fc8749-1091-4bcf-97ad-c3051f3f7174.png)
