### ISSUE TITLE
EgressProvider only works when a process is marked as isDefault

### ISSUE THREAD

**Issue by johan-bjerling** [dotnet/dotnet-monitor#2123]
### Description

If your donet-monitor is collecting and has no default process, providing an egressProvider to the dump endpoint won't egress a dump, but instead serve it via the HTTP response stream. 

If you instead ensure your process is selected as default then your egressProvider param works and a dump is egressed.

I assume this is a bug, but if this is working as intended, then the docs ought to specify this. 

#### Prereqs
- Have a working egressProvider setup to write to an Azure storage blob. 

#### Broken scenario

Ensure there's a dotnet process running and that dotnet-monitor has no process picked as default.

1. Launch `dotnet-monitor collect --no-auth`
1. Verify that no process is selected as default: `curl -k https://localhost:52323/processes`
1. Run a dump, specifying pid and egressProvider: `curl -k https://localhost:52323/dump?pid=<YourPid>&egressProvider=MonitorBlob`
1. The results will be similar to this: `[1] 1475`
1. After dump is finished you'll get something like this: 
```
$ Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file. 
```
Nothing will be uploaded to the blob, as instead dotnet-monitor has decided to serve you the dump to your HTTP response stream.

#### Working scenario

Ensure there's a dotnet process running that dotnet-monitor picks up as default.

1. Launch `dotnet-monitor collect --no-auth`
1. Verify that a process is selected as default: `curl -k https://localhost:52323/processes`
1. Run a dump, specifying egressProvider only: `curl -ik https://localhost:52323/dump?egressProvider=MonitorBlob`
1. The results will be similar to this: 
```
HTTP/1.1 202 Accepted
Content-Length: 0
Date: Fri, 15 Jul 2022 09:02:24 GMT
Server: Kestrel
Location: https://localhost:52323/operations/3f02c22f-48b9-42d9-84ec-c05d9f9386b1
```
Once the operation has finished you'll get a dump uploaded to your blob.

### Configuration

Dotnet-monitor version: 6.2.0+7a78ee4c4fe982bb380a517408326391f2fcae57
Running on Windows 10, but also reproducable in AKS dotnet-monitor as a sidecar.

**Comment by jander-msft** [comment]
I'm not able to reproduce this issue with dotnet-monitor.

However, I have a hunch as to what is happening. If you are using a shell such as Powershell to execute the curl commands, the shell is interpreting the `&` in `curl -k https://localhost:52323/dump?pid=<YourPid>&egressProvider=MonitorBlob` as a separator between two commands. This effectively invokes `curl -k https://localhost:52323/dump?pid=<YourPid>` first (which would send the artifact through the reponse stream) and then tries to invoke `egressProvider=MonitorBlob` as a separate command.

Instead, if you execute it as `curl -k "https://localhost:52323/dump?pid=<YourPid>&egressProvider=MonitorBlob"`, then the shell does not interpret the ampersand and the artifact is egressed through the specified provider.

**Comment by johan-bjerling** [comment]
> I'm not able to reproduce this issue with dotnet-monitor.
> 
> However, I have a hunch as to what is happening. If you are using a shell such as Powershell to execute the curl commands, the shell is interpreting the `&` in `curl -k https://localhost:52323/dump?pid=<YourPid>&egressProvider=MonitorBlob` as a separator between two commands. This effectively invokes `curl -k https://localhost:52323/dump?pid=<YourPid>` first (which would send the artifact through the reponse stream) and then tries to invoke `egressProvider=MonitorBlob` as a separate command.
> 
> Instead, if you execute it as `curl -k "https://localhost:52323/dump?pid=<YourPid>&egressProvider=MonitorBlob"` (note the double quotes around the entire URL), then the shell does not interpret the ampersand and the artifact is egressed through the specified provider.

Wow, you're completely right! I feel like a fool now. 

I was using Bash, not Powershell, but the same behaviour occurred. Surrounding the url with double quotes was all that was needed! 🤦‍♂️ 

Thanks for you help and sorry about the late (I was away on holiday), closing this now!
