### ISSUE TITLE
Create a configuration schema for dotnet-monitor

### ISSUE THREAD

**Issue by shirhatti** [dotnet/dotnet-monitor#23]

**Comment by shirhatti** [comment]
I took an initial stab at it by basing it off the ASP.NET schema. Try:

```json
{
  "$schema": "https://gist.githubusercontent.com/shirhatti/880c71e47dc95d9099df1b240119850f/raw/d72b3d32d6554d9a9ce88ed0dbef06b894476cbe/settings.json"
}
```

**Comment by shirhatti** [comment]
https://aka.ms/dotnet-monitor-schema

**Comment by shirhatti** [comment]
I just realized this schema doesn't include ASP.NET Core schema. No completions for any kestrel server options 😭

**Comment by jander-msft** [comment]
> I just realized this schema doesn't include ASP.NET Core schema. No completions for any kestrel server options 😭

I wonder if we can do something like:
```
{
  "allOf": [
    { "$ref": "<address of asp.net schema so we don't have to do it ourselves>" },
    { <dotnet-monitor specific schema> }
  ]
}
```

for the dotnet-monitor schema.

**Comment by jander-msft** [comment]
I looked at https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/appsettings.json as an example, and it's got a lot more than we'd want (also 3rd party properties) and yet doesn't have enough of the more standard properties, such as console logging and event logging objects. So maybe we do need to maintain our own self-contained schema with the more common ASP.NET Core properties.

**Comment by wiktork** [comment]
I think we're approaching this the wrong way; us maintaining or referencing asp.net schema shouldn't be necessary. We should:
- Rely on tools to support multiple schemas. (And probably make sure we are not restrictive in our schema if users want to combine settings)
- Possibly support more than 1 settings file, to make it easier to configure disparate settings.

**Comment by wiktork** [comment]
Sample multi-schema in vs code settings:
    "json.schemas": [
    {
        "fileMatch": [
            "settings.json"
        ],
        "url": "https://aka.ms/dotnet-monitor-schema",

    },
    {
        "fileMatch": [
            "settings.json"
        ],
        "url": "https://json.schemastore.org/appsettings"
    }
    ],

**Comment by jander-msft** [comment]
I tried searching a bit for how to do something similar in Visual Studio (not Code) and all I've been able to find is specifying $schema in the json file.

**Comment by kelltrick** [comment]
Close this and make a new issue to track the additional kestrel schema work. @wiktork
