### ISSUE TITLE
Histogram data not showing when running dotnet-counters

### ISSUE THREAD

**Issue by Jarek300** [dotnet/dotnet-monitor#2317]
### Description
Histogram data is not showing when running dotnet-counters contrary to [documentation](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation#example-of-different-instrument-types).

Also decribed [here](https://github.com/dotnet/docs/issues/30255).

### Configuration
dotnet-monitor 6.0.0+9b21f76a1fff86a72ef1557f9fddc78695970332
.NET 6.0.8. Visual Studio 17.3.0.
Windows 11

**Comment by jander-msft** [comment]
The `dotnet monitor` tool currently does not support collecting metrics from `System.Diagnostics.Metrics`. The documentation that you have linked to does not say this is supported in `dotnet monitor` either. A work item already exists for adding support for this: #329
