### ISSUE TITLE
Examples for Custom Metrics configuration in AKS

### ISSUE THREAD

**Issue by alcallah** [dotnet/dotnet-monitor#242]
### Documentation Request

In the documentation page for Configuration, it mentions all the different options for specifying Configuration values for metrics in dotnet-monitor (command line parameters, user settings, key-per-file, and environment variables). It also mentions that you can specify the dotnet-monitor configuration through a config map in Kubernetes, yet in the Kubernetes section it only specifies an example for a Kubernetes secrets. Since I am only looking to add custom metrics to dotnet-monitor, it would be more helpful if we can have an example for specifying dotnet-monitor configuration in Kubernetes using config maps with the recommended guidance.

### Previous documentation

https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#Kubernetes

**Comment by wiktork** [comment]
@shirhatti I believe you had plans to add this, per https://github.com/dotnet/dotnet-monitor/pull/206/files#r616877616

**Comment by wiktork** [comment]
Also related to #164
