### ISSUE TITLE
Q: gcdump x-plat tool

### ISSUE THREAD

**Issue by tmds** [dotnet/dotnet-monitor#243]
Is there a tool that runs on Linux to analyze the gcdump files produced by the `/gcdump` endpoint?

cc @adamsitnik, do you know?

**Comment by adamsitnik** [comment]
I don't, but @noahfalk should know.

**Comment by noahfalk** [comment]
dotnet-gcdump has a little bit of analysis capability:
https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-gcdump#dotnet-gcdump-report-gcdump_filename

cc @shirhatti @josalem

**Comment by tmds** [comment]
Thanks. I'll check that out!
