### ISSUE TITLE
Make trace profile names consistent between dotnet-monitor and dotnet-trace

### ISSUE THREAD

**Issue by shirhatti** [dotnet/dotnet-monitor#26]
From @noahfalk 

> Feedback on dotnet-monitor itself: 'Http' could also easily be interpretted as the http client code in the BCL rather than the Http server code in Kestrel. We may want to consider a less generic name.
We should also look at how names here align with names in dotnet-trace --profile. I don't think we want two different sets of named policies.

**Comment by jander-msft** [comment]
Tracking more profiles being added to dotnet-trace: https://github.com/dotnet/diagnostics/pull/2132

**Comment by jander-msft** [comment]
Preserve existing names and add new names.

**Comment by wiktork** [comment]
If this is confusing in the future, we will add aliases to our profile names.
