### ISSUE TITLE
Can the dotnet-monitor image run directly for testing?

### ISSUE THREAD

**Issue by AloisKraus** [dotnet/dotnet-monitor#2908]
### Documentation Request

I want to run the dotnet-monitor docker image directly like 

`docker run -it --entrypoint dotnet-monitor mcr.microsoft.com/dotnet/monitor:7 collect --no-auth`

When I try to access the endpoints via curl I get not even a connection:

```
curl  http://localhost:52325 
curl: (7) Failed to connect to localhost port 52325 after 2226 ms: Connection refused

curl  http://localhost:52323/processes 
curl: (7) Failed to connect to localhost port 52323 after 2252 ms: Connection refused
```

It looks like I am missing something obvious here. How are these docker images supposed to be used? 

Another quick try is to run dotnet-monitor inside an existing container. I have added dotnet-monitor to my docker image and added a shell script as entry point

```
#!/bin/bash

# Start in background
dotnet LinuxWebApplication.dll &
  
export ASPNETCORE_URLS=http://+:52323

# Start monitoring process
# https://localhost:52323/processes

# Unset ASPNETCORE_URLS from aspnet base image
export ASPNETCORE_URLS=
# Disable debugger and profiler diagnostics to avoid diagnosing self.
export COMPlus_EnableDiagnostics=0
# Default Filter
export DefaultProcess__Filters__0__Key=ProcessId
export DefaultProcess__Filters__0__Value=1
# Remove Unix Domain Socket before starting diagnostic port server
export DiagnosticPort__DeleteEndpointOnStartup=true
# Server GC mode
export DOTNET_gcServer=1
# Logging: JSON format so that analytic platforms can get discrete entry information
export Logging__Console__FormatterName=json
# Logging: Use round-trip date/time format without timezone information (always logged in UTC)
export Logging__Console__FormatterOptions__TimestampFormat=yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff'Z'
# Logging: Write timestamps using UTC offset (+0:00)
export Logging__Console__FormatterOptions__UseUtcTimestamp=true

dotnet-monitor collect --no-auth 
```

There I also get access denied when I try to access processes. I assume with --no-auth I should be able to connect. One trick which I have not found yet seems to be missing here as well. 

### Previous documentation

All existing documentation deals with kubernetes which not everyone has up and running just for a quick test. Some basic examples should exist to get one started. The local deployment is a good start: https://www.hanselman.com/blog/exploring-your-net-applications-with-dotnetmonitor but for dotnet-monitor I really  would like a similar nice intro.

**Comment by jander-msft** [comment]
You'll need to [expose](https://docs.docker.com/engine/reference/run/#expose-incoming-ports) the ports you want to access from outside of the container, namely 52323 and 52325.
