### ISSUE TITLE
CPU Usage Ratio Explanation

### ISSUE THREAD

**Issue by learnernk** [dotnet/dotnet-monitor#2933]
Hi

I am trying to configure the dotnet monitor cpu usage ratio for alerts. However, I was not able to find any proper information on this.

Could you kindly explain what dotnet_systemruntime_cpu_usage_ratio entails? What is the ratio here and how is it calculated? If you could point me to any documentation that would be very helpful.

**Comment by learnernk** [comment]
> Hi, if I'm understanding you correctly then this might be helpful: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters, specifically the `cpu-usage` counter under System.Runtime counters.

Hi Thank you for prompt reponse. Yes, I have looked at this but this refers to cpu-usage, whereas the dotnet monitor has dotnet_systemruntime_**cpu_usage_ratio**. What is the ratio for how is it calculated?

<img width="761" alt="image" src="https://user-images.githubusercontent.com/102992681/204993253-04485c70-b5d0-4100-8572-9a064c56af1a.png">

**Comment by jander-msft** [comment]
> > Hi, if I'm understanding you correctly then this might be helpful: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/available-counters, specifically the `cpu-usage` counter under System.Runtime counters.
> 
> Hi Thank you for prompt reponse. Yes, I have looked at this but this refers to cpu-usage, whereas the dotnet monitor has dotnet_systemruntime_**cpu_usage_ratio**. What is the ratio for how is it calculated?

Dotnet-monitor is not calculating anything in regard to this counter but merely forwarding the data as-is in the Prometheus exposition format.

The target runtime instance is reporting the unit of the measurement (in this case, calling it `ratio`). Dotnet-monitor names all of the metrics as `<providerName>_<counter_name>_<unit>`.

You can see from the description of the `cpu-usage` counter in the docs that you highlighted and even in the [source code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs#L87) that the `cpu-usage` counter is a percent. Percentages are ratios of the same unit.
