### ISSUE TITLE
Dump file will not open in Visual Studio

### ISSUE THREAD

**Issue by noelmcgrath** [dotnet/dotnet-monitor#3175]
### Description
I have taken a dump file from a fargate dotnet container via running dotnet monitor as a sidecar.

Running the following command:
`curl.exe 'http://10.1.5.126:52323/dump?pid=1&type=Full' --output myfile`

This saves the file to my local windows machine but when i try to open in Visual Studio I get error:
Value cannot be null.
Parameter name :v1

Also tried open with and selected "Managed Linux Core Dump File Summary"
same error.

Don't know what else to add here, have watched [Diagnosing memory leaks in .NET apps](https://www.youtube.com/watch?v=SHGeE_PFA4s&ab_channel=dotnet), and it looks straight forward

1. Take dump file
2. open file in Visual Studio

### Configuration
Using 
mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.16 for application 
mcr.microsoft.com/dotnet/monitor:6 for sidcar container
Visual Studio Version 17.4.2

### Other information
Dont want to add dump file as its a company product

**Comment by jander-msft** [comment]
Try using [dotnet-dump analyze](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump#dotnet-dump-analyze) to see if you can open the file and find some information successfully. If that works, I would suggest logging an issue on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/home) as it would likely be an issue with Visual Studio.

**Comment by noelmcgrath** [comment]
Seems like an issue with Visual Studio: [Unable to open Linux dump files in Visual Studio 2022 17.4](https://developercommunity.visualstudio.com/t/Unable-to-open-Linux-dump-files-in-Visua/10225926?ftype=problem&q=linux+dump+file)

**Comment by jander-msft** [comment]
Closing since there is no action to take for `dotnet monitor`.
