### ISSUE TITLE
Issues with SSL + compression

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#330]
Dotnet-monitor with http respects brotli compression, but takes much longer to complete. 

C:\Users\wiktork.REDMOND>curl -H "Accept-Encoding: br" http://localhost:52323/dump/22496 -o test.dmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4482k    0 4482k    0     0  37936      0 --:--:--  0:02:01 --:--:--  192k

This feels pretty awful for the local scenario. 

Hosting over https, br is ignored altogether:

C:\Users\wiktork.REDMOND>curl -H "Accept-Encoding: br" https://localhost:52323/dump/22496 -o test.dmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 74.7M    0 74.7M    0     0  5468k      0 --:--:--  0:00:14 --:--:-- 17.4M

**Comment by jander-msft** [comment]
Compression was removed in either preview 8 or RC1, so I think this issue is moot.
