### ISSUE TITLE
Make MonitorApiKey length configurable

### ISSUE THREAD

**Issue by kelltrick** [dotnet/dotnet-monitor#359]
## Background and Motivation

The MonitorApiKey muse be exactly 32 bytes long, as defined in [ApiKeyAuthenticationHandler.cs:66](https://github.com/dotnet/dotnet-monitor/blob/5f97a7154a1d2f6bc33fbd0a848cdb253e784cb1/src/Tools/dotnet-monitor/Auth/ApiKeyAuthenticationHandler.cs#L68). We only require the user to tell us what the hash of that key is during configuration, so we shouldn't care what length this value is.

## Proposed Feature

- Change `ApiKeyAuthenticationHandler.cs` to allow keys of any length between 32 bytes and 2048 bytes.
- Place an additional max cap of `((2048 * 8) / 6) + 2` bytes in the raw base64 encoded Authorization parameter.

## Usage Examples

1. Using a 128 byte MonitorApiKey with SHA512:
```
Authorization: MonitorApiKey lmWOJfSJRXO/6Vge40O3KdW/VunK2btVg9VTvSiGUM7zZueihJhIjDhCi3M56/D1bxCf7YB0duCV89zmCYoeiu4RUEshS82zME5TEKInMukbaPZvT6euQyqCyHIqc69FMchdfFv1CkD1n2AnLh2XKqQOrJBfJPShkeUKo8C/Dks=
```
```
"ApiAuthentication": {
  "ApiKeyHash": "7F78E57A36A46C531451278DC100084EB4D093A9FA05F16E25CF122166239FC94837931795CE49582A3C3FA477B3EB3944010BEE943AC961C369DE80B02A8409",
  "ApiKeyHashType": "SHA512"
},
```
2. Using a 32 byte MonitorApiKey with SHA256
```
Authorization: MonitorApiKey kRh/TVsGw/sxoP7eE2cLmxNZu+H+em1oWOfbF4902XI=
```
```
"ApiAuthentication": {
  "ApiKeyHash": "5395C7FD870DFA6F61BEBBA86134A7F9A0125D36677FBD091C7E5150ACC4E16D",
  "ApiKeyHashType": "SHA256"
},
```

**Comment by jander-msft** [comment]
I would separate this into two issues:
1) allowing the Authorization header to contain a key that is longer than 32 bytes.
2) allowing the key generation to be configurable.

Because the first is probably a bug and the second is an enhancement.
