### ISSUE TITLE
According to docu, S3 Egress Provider is available in `release/7.0` and `release/7.x` but it's actually not in source code

### ISSUE THREAD

**Issue by nx-s** [dotnet/dotnet-monitor#3694]
### Description

See Documentation:
https://github.com/dotnet/dotnet-monitor/blob/release/7.0/documentation/configuration/egress-configuration.md#s3-storage-egress-provider

But in source folder:
https://github.com/dotnet/dotnet-monitor/tree/release/7.0/src/Tools/dotnet-monitor/Egress

only AzureBlob & FileSystem can be found.

Seems merging went wrong? I'd like to see the S3 egressProvider in release Version 7.

**Comment by jander-msft** [comment]
Documentation should be updated to reflect that this is only available in 8.0+
