### ISSUE TITLE
perf trace endpoint

### ISSUE THREAD

**Issue by verdie-g** [dotnet/dotnet-monitor#3760]
## Background and Motivation

Tools such as `dotnet-trace` only capture managed code. By using perf (1), we could also see native code (epoll, GC, libc, ...).

## Proposed Feature

Add a new endpoint that would generate a flamegraph from perf cycles event.

```
POST /perf/flamegraph?pid={pid}&durationSeconds={durationSeconds}&egressProvider={egressProvider}&tags={tags}
```

that would run

```
perf script flamegraph -F 999 -e cycles -p $pid sleep $durationSeconds
```

and return the generated flamegraph.html.

If perf is run with elevated privileges, we could also get the kernel stacks which is very valuable.

It would also be interesting to return a pprof instead of the html so it can be used by profile aggregators such as [Phlare](https://grafana.com/oss/phlare).

## Usage Examples

I have some performance issues but I can't see anything obvious in dotnet-trace, then I would use
```
POST /perf/flamegraph?pid=1255&durationSeconds=30
```
and I could potentially find the reason in native code.

**Comment by jander-msft** [comment]
It's unlikely that we will add platform-specific tooling support to dotnet-monitor as it is focused on enabling collection of diagnostics from .NET. However, you can still invoke executables found in the same filesystem as dotnet-monitor using the `Execute` action in collection rules: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/collection-rule-configuration.md#execute-action
