### ISSUE TITLE
Metrics endpoint is not working?

### ISSUE THREAD

**Issue by dominikjeske** [dotnet/dotnet-monitor#384]
I'm trying to get metrics of sample app (without containers - pure metal) but is seems that this option is not working for me. I'm using version 5.0.0-preview.4.21219.3 and I have configured dotnet monitor just like in docs - by using **DefaultProcess** with help of schema

![image](https://user-images.githubusercontent.com/3872348/120534983-bd3f4e80-c3e2-11eb-8a12-1ee72d662b20.png)

When I'm calling http://localhost:52325/metrics I'm getting empty results (but I can see each request in cmd). Metrics endpoint Is working only when there is only one dotnet process (but not on first request) - when there are many processes this endpoint is not working. The other weird thing is that according to schema DefaultProcess section should be side by side with metrics but when I'm invoking `dotnet monitor config show` this section is not displayed. When I moved this section inside Metrics it is displayed from `dotnet monitor config show` but unfortunately I can't get any metrics.

![image](https://user-images.githubusercontent.com/3872348/120536829-d77a2c00-c3e4-11eb-95ef-a630f7f0378b.png)

**Comment by jander-msft** [comment]
The default process configuration is not available in the Preview 4 version but will be available in the upcoming Preview 5 version.

The Preview 4 (and prior) behavior, as you have observed, is that if there is more than one (or no) processes, then the `/metrics` route will not return data. Starting in Preview 5, the selected process can be configured using the default process configuration, which allows for more controlled determination of what the default process is for metrics and for other routes where the process identifier is optional.

If you'd like to use the latest preview 5 version, you can install it with the following command:
```
dotnet tool install -g dotnet-monitor --version 5.0.0-preview.5.* --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools%40Local/nuget/v3/index.json
```

I'll follow up on this issue when the final Preview 5 version has shipped.

**Comment by dominikjeske** [comment]
Preview5 is working as expected. Thanks.
