### ISSUE TITLE
Empty list of processes for dotnet application run in Kubernetes

### ISSUE THREAD

**Issue by kevin-mcmanus** [dotnet/dotnet-monitor#411]
I'm currently trying to get dotnet-monitor running against one of our production applications running in Kubernetes.  I've updated the manifest.yml file to include the sidecar and can successfully hit the `/processes` endpoint with a 200 response with port-forwarding enabled.  The problem is that it returns an empty array `[]`.  I've also tried the `/metrics` endpoint.  This returns a 200 with an empty payload (presumably because it can't find a process to attach to).

Running `ps aux` on my pod I can see a handful of running processes, but only one dotnet one.
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1 19.3  0.4 5047936 140960 ?      Ssl  14:57   0:53 dotnet Application.dll --RemoteConfigurationSources:0:BaseUri=http://config/current --Microservice:Configura
root        28  0.0  0.0   2396   776 pts/0    Ss   15:00   0:00 sh -c clear; (bash || ash || sh)
root        34  0.0  0.0   2396   120 pts/0    S    15:00   0:00 sh -c clear; (bash || ash || sh)
root        35  0.0  0.0   4008  3288 pts/0    S+   15:00   0:00 bash
root        38  0.0  0.0   2396   780 pts/1    Ss   15:02   0:00 sh -c clear; (bash || ash || sh)
root        44  0.0  0.0   2396   124 pts/1    S    15:02   0:00 sh -c clear; (bash || ash || sh)
root        45  0.0  0.0   4008  3304 pts/1    S    15:02   0:00 bash
root       363  0.0  0.0   7648  2772 pts/1    R+   15:02   0:00 ps aux
```

Viewing the logs on the dotnet-monitor side car I can see that the endpoint has been hit and no sign of an error.
```
{"Timestamp":"2021-06-08T14:57:42.2399578Z","EventId":13,"LogLevel":"Warning","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.","State":{"Message":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments.","{OriginalFormat}":"WARNING: Authentication has been disabled. This can pose a security risk and is not intended for production environments."},"Scopes":[]}
{"Timestamp":"2021-06-08T14:57:43.0497672Z","EventId":0,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Overriding address(es) \u0027http://*:52323\u0027. Binding to endpoints defined in UseKestrel() instead.","State":{"Message":"Overriding address(es) \u0027http://*:52323\u0027. Binding to endpoints defined in UseKestrel() instead.","addresses":"http://*:52323","methodName":"UseKestrel()","{OriginalFormat}":"Overriding address(es) \u0027{addresses}\u0027. Binding to endpoints defined in {methodName} instead."},"Scopes":[]}
{"Timestamp":"2021-06-08T14:57:43.1444660Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://[::]:52323","State":{"Message":"Now listening on: http://[::]:52323","address":"http://[::]:52323","{OriginalFormat}":"Now listening on: {address}"},"Scopes":[]}
{"Timestamp":"2021-06-08T14:57:43.1445561Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://[::]:52325","State":{"Message":"Now listening on: http://[::]:52325","address":"http://[::]:52325","{OriginalFormat}":"Now listening on: {address}"},"Scopes":[]}
{"Timestamp":"2021-06-08T14:57:43.2359365Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Application started. Press Ctrl\u002BC to shut down.","State":{"Message":"Application started. Press Ctrl\u002BC to shut down.","{OriginalFormat}":"Application started. Press Ctrl\u002BC to shut down."},"Scopes":[]}
{"Timestamp":"2021-06-08T14:57:43.2360486Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Hosting environment: Production","State":{"Message":"Hosting environment: Production","envName":"Production","{OriginalFormat}":"Hosting environment: {envName}"},"Scopes":[]}
{"Timestamp":"2021-06-08T14:57:43.2360767Z","EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Content root path: /app/.store/dotnet-monitor/5.0.0-preview.5.21302.5/dotnet-monitor/5.0.0-preview.5.21302.5/tools/netcoreapp3.1/any/","State":{"Message":"Content root path: /app/.store/dotnet-monitor/5.0.0-preview.5.21302.5/dotnet-monitor/5.0.0-preview.5.21302.5/tools/netcoreapp3.1/any/","contentRoot":"/app/.store/dotnet-monitor/5.0.0-preview.5.21302.5/dotnet-monitor/5.0.0-preview.5.21302.5/tools/netcoreapp3.1/any/","{OriginalFormat}":"Content root path: {contentRoot}"},"Scopes":[]}
{"Timestamp":"2021-06-08T14:59:20.8438118Z","EventId":5,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Monitoring.RestServer.Controllers.DiagController","Message":"Written to HTTP stream.","State":{"Message":"Written to HTTP stream.","{OriginalFormat}":"Written to HTTP stream."},"Scopes":[{"Message":"ConnectionId:0HM9AHNV9FJA9","ConnectionId":"0HM9AHNV9FJA9"},{"Message":"RequestPath:/processes RequestId:0HM9AHNV9FJA9:00000001, SpanId:|51cc742b-43f7c8beade0de05., TraceId:51cc742b-43f7c8beade0de05, ParentId:","RequestId":"0HM9AHNV9FJA9:00000001","RequestPath":"/processes","SpanId":"|51cc742b-43f7c8beade0de05.","TraceId":"51cc742b-43f7c8beade0de05","ParentId":""},{"Message":"Microsoft.Diagnostics.Monitoring.RestServer.Controllers.DiagController.GetProcesses (Microsoft.Diagnostics.Monitoring.RestServer)","ActionId":"f3e52221-60fd-48cd-89ef-451e93954fdb","ActionName":"Microsoft.Diagnostics.Monitoring.RestServer.Controllers.DiagController.GetProcesses (Microsoft.Diagnostics.Monitoring.RestServer)"}]}
```

I'm running against the following image  and have previously tried the `.1` release too.
```
mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.5
```

I've tried running the same manifest.yml config against many of our other applications and these all work well.  The application in question is running dotnet core 3.1, as are the other apps that I've tested this on.

I've upped the dotnet-monitor logging to `debug` but this doesn't give any extra information of use.

I've also compiled dotnet-monitor locally on Windows (no docker/kubernetes), along with my production application (again running locally in Windows) and been able to successfully return the process from the endpoint. 

Do you know what might be causing this behaviour?

Appreciate that I haven't given you a lot to go on here.  I've spend a day building lots of sample apps to replicate the problem but can't find the right combination.  Is there any additional logging that I could use to diagnose the problem?  If you could point me at some build instructions to generate the required docker image locally, I'm happy to add the logging myself and see where this is failing.  (Sadly I can't even spot a docker file in this repo).

**Comment by jander-msft** [comment]
> I've tried running the same manifest.yml config against many of our other applications and these all work well. The application in question is running dotnet core 3.1, as are the other apps that I've tested this on.

Could you check the environment block of the process that is running the .NET Core 3.1 application? It might have an environment variable named `COMPlus_EnableDiagnostics`; if its value is `0`, then dotnet-monitor (or any of the other diagnostic tools from https://github.com/dotnet/diagnostics) will not be able to discover the process.

Also, if you could provide your manifest.yml content, that might help us diagnose the issue further. Feel free to remove any secrets or sensitive information from it before providing it.

> Is there any additional logging that I could use to diagnose the problem?

At this time, I don't think we can get additional logging for the process enumeration algorithm. I'll look into adding more detailed logging for this in a future version.

> If you could point me at some build instructions to generate the required docker image locally, I'm happy to add the logging myself and see where this is failing. (Sadly I can't even spot a docker file in this repo).

As with the other images produced by the dotnet team, the Dockerfiles are in the https://github.com/dotnet/dotnet-docker repository. The nightly Dockerfile for dotnet-monitor is located at https://github.com/dotnet/dotnet-docker/blob/nightly/src/monitor/5.0/alpine/amd64/Dockerfile

**Comment by kevin-mcmanus** [comment]
Thanks for the prompt reply.  Knowing where to find the dockerfile was really useful and enabled me to add enough logging to identify the root cause.

From the logging I could see that a process was initially returned in the `MetricsService.ExecuteAsync()` while loop, but it quickly disappeared.  It turned out that the application code (a console app hosted by Generic Host) was calling an `async` method that wasn't being awaited in `public static void Main()`.  Changing the method signature to `public static async Task Main()` and adding the `await` solved the problem.

My process was still running (as could be seen using `ps aux` and data flowing through the connected data stores) but was being dropped by dotnet-monitor.  I'm not sure if this should be expected behaviour or not.

As for why it was working on some applications and not others, this was down to the async call being made in a NuGet that had been applied in some repos but not others.  I'm a little less clear why I couldn't reproduce in Visual Studio/Windows; gut feel is due to a difference in how the interactivity settings of the two respective consoles have been configured or Visual Studio hanging on to the process for longer.

**Comment by jander-msft** [comment]
Closing because issue was resolved. Let us know if you have any other issues, feedback, proposals, etc for dotnet-monitor!
