### ISSUE TITLE
Allow customers to enable the Preview 4 style default process selection algorithm

### ISSUE THREAD

**Issue by willpe** [dotnet/dotnet-monitor#416]
## Background and Motivation

In Preview 5, dotnet monitor added support to specify default processes by a selection of identifiers including process name and command line. This kind of default process selection works well when the actor configuring dotnet monitor and the actor deploying the application are the same - when you know the app that will be deployed ahead of time. The old behavior (in Preview 4 and before) selected the only dotnet process running (if one exists), which could lead to non-determinism. However, the old behavior worked well in cases where a hosting provider was configuring dotnet monitor in an environment where only a single dotnet process would be running. For those customers, the new behavior does not allow them to arbitrarily select any dotnet process without knowing some of its identify information.

## Proposed Feature

Provide a mechanism in configuration to select the only dotnet monitor process as the default rather than a specific, identified process. The preview 4 (and before) behavior was non-deterministic, and it would be assumed this new behavior maintains that characteristic, too.

**Comment by jander-msft** [comment]
Rather than adding the previous behavior back to the configuration, a good candidate using the existing process filter mechanism is to filter to the process name of 'dotnet':

```json
"DefaultProcess": {
    "Filters": [{
        "Key": "ProcessName",
        "Value": "dotnet"
    }]
}
```
While it is not completely equivalent, we believe that this is sufficient for those who were relying on the previous behavior.
