### ISSUE TITLE
Documentation for configuring dotnet-monitor logging

### ISSUE THREAD

**Issue by alcallah** [dotnet/dotnet-monitor#424]
### Documentation Request

We are currently using dotnet-monitor to collect some metrics for our service. However, I noticed that dotnet-monitor emits logs for every time it writes into the metrics endpoint. Is there any way to configure the logging verbosity of dotnet-monitor? I would appreciate adding documentation on how to do this.

**Comment by wiktork** [comment]
@jander-msft I expected to be able to remove metrics logging with:
Logging__LogLevel__Microsoft.Diagnostics.Monitoring.RestServer.Controllers.MetricsController

but I'm still seeing logging from Microsoft.Diagnostics.Monitoring.RestServer.OutputStreamResult. We should consider using the parent controller category for OutputStreamResult.

@alcallah Logging levels are controlled by configuration, such as configuration described in https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0

Are you on Aks? Our default log levels are defined at https://github.com/dotnet/dotnet-monitor/blob/main/src/Tools/dotnet-monitor/appsettings.json and deployed alongside the app. The easiest way that I can think of to tweak log levels is to mount a file into /etc/dotnet-monitor where we read configuration from. So you might have something like:

`/etc/dotnet-monitor/Logging__LogLevel__Microsoft.Diagnostics.Monitoring.RestServer.Controllers.MetricsController` with the contents of `Error`. Replace `Microsoft.Diagnostics.Monitoring.RestServer.Controllers.MetricsController` with whatever category you wish to change.

**Comment by jander-msft** [comment]
I believe that @wiktork has provided the appropriate guidance to answer your questions and I've created a separate issue to consolidate and document the logger categories. Feel free to reopen if you need more help with this specific issue.
