### ISSUE TITLE
Hello, my dotnet monitor configuration is not working, can you help me? Thank you very much

### ISSUE THREAD

**Issue by gzj132** [dotnet/dotnet-monitor#4249]
Hello, my dotnet monitor configuration is not working, can you help me? Thank you very much
![D432BEE0-2856-43E8-89AC-E31E289AEFA7](https://user-images.githubusercontent.com/50973061/231916135-eb9b8f2f-259e-498f-904c-2acb4d2cd5b8.jpeg)

**Comment by jander-msft** [comment]
Please try `dotnet-monitor config show --show-sources` for it to write out where each value came from.

What is the path of your configuration file that you have on the left side? It may be in the wrong place and dotnet-monitor doesn't know how to locate it.

**Comment by gzj132** [comment]
> Please try `dotnet-monitor config show --show-sources` for it to write out where each value came from.
> 
> What is the path of your configuration file that you have on the left side? It may be in the wrong place and dotnet-monitor doesn't know how to locate it.

srr，I did not find this command on windows system

**Comment by jander-msft** [comment]
It's documented [here](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/view-merged-configuration.md) and has been available since [6.2.0](https://github.com/dotnet/dotnet-monitor/releases/tag/v6.2.0). If you do not have this command, please update your .NET Monitor installation; 6.3.2 and 7.1.1 are the currently supported versions for each major version.

**Comment by gzj132** [comment]
> It's documented [here](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/view-merged-configuration.md) and has been available since [6.2.0](https://github.com/dotnet/dotnet-monitor/releases/tag/v6.2.0). If you do not have this command, please update your .NET Monitor installation; 6.3.2 and 7.1.1 are the currently supported versions for each major version.

ok，thanks。

**Comment by gzj132** [comment]
> It's documented [here](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/view-merged-configuration.md) and has been available since [6.2.0](https://github.com/dotnet/dotnet-monitor/releases/tag/v6.2.0). If you do not have this command, please update your .NET Monitor installation; 6.3.2 and 7.1.1 are the currently supported versions for each major version.

I upgraded dotnet-monitor to 6.3.2, then the first picture is my configuration, the second picture is I built a simple project, I added environment variables when the project started, but my dotnet-monitor still does not work, can you help me
![73DD848E-88C4-43D8-BF67-D379EBDB0170](https://user-images.githubusercontent.com/50973061/232438990-7e7149e9-f3ca-473c-a531-89ca69bc831c.jpeg)
![5A276E3A-E5F4-4D96-A964-F800FA29301C](https://user-images.githubusercontent.com/50973061/232439005-d9fa3d47-4211-451f-a534-c53c961f10c6.jpeg)

**Comment by gzj132** [comment]
> The `DOTNET_DiagnosticPorts` environment variable needs to be set at process launch, not in the main method of you application (it's too late by that point and won't be observed by the runtime). If you just debug launching this in Visual Studio, set the environment variable on the [launch profile](https://learn.microsoft.com/en-us/visualstudio/debugger/project-settings-for-csharp-debug-configurations-dotnetcore?view=vs-2022#launch-profile-net-core-net-5).

My dotnet monitor has started to work, thank you for your help, have a good life
