### ISSUE TITLE
When I changed the listener mode and EndpointName, it didn't work

### ISSUE THREAD

**Issue by gzj132** [dotnet/dotnet-monitor#4307]
My dotnet-monitor works in the docker container of linux system. Instead of pulling from the image, I directly use dotnet tool in the docker container
![F710191E-C58F-4442-8B03-83473B7293A8](https://user-images.githubusercontent.com/50973061/233971131-aab8eae7-a588-4e1b-8c5e-7ea5b562d51f.jpeg)
![E8D5B977-CC6D-457E-82C3-A3ECE337966B](https://user-images.githubusercontent.com/50973061/233971148-79a775d7-3a78-402c-8746-487e897f87d0.jpeg)

**Comment by jander-msft** [comment]
If this socket file is stale from a prior instance of dotnet-monitor, you are certain that it is a stale file, and you think this is a common automated occurrence, you can set `DotnetMonitor_DiagnosticPort__DeleteEndpointOnStartup` environment variable or set the corresponding one in configuration to `true`: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/schema.json#L1065 (either of these will instruct the new dotnet-monitor instance to delete the existing Unix domain socket file before starting its server).

**Comment by gzj132** [comment]
> If this socket file is stale from a prior instance of dotnet-monitor, you are certain that it is a stale file, and you think this is a common automated occurrence, you can set `DotnetMonitor_DiagnosticPort__DeleteEndpointOnStartup` environment variable or set the corresponding one in configuration to `true`: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/schema.json#L1065 (either of these will instruct the new dotnet-monitor instance to delete the existing Unix domain socket file before starting its server).

Thank you again, my monitor can run. Since I didn't create a port folder in windows deployment before, I can run it. Have a nice day
