### ISSUE TITLE
Consider not relying on EventPipe for getting a dump on Linux

### ISSUE THREAD

**Issue by LakshanF** [dotnet/dotnet-monitor#4534]
`NativeAOT EventPipe `is not planning on supporting [CreateCoreDump](https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#Dump-Commands) command. It looks like dotnet-monitor doesn't rely on `EventPipe `for [generating a dump for Windows](https://github.com/dotnet/dotnet-monitor/blob/80ab7a8d41d0a19e068a41f6ecb6d0578fcc2dc8/src/Microsoft.Diagnostics.Monitoring.WebApi/DumpService.cs#L66-L76). Would it be possible to switch for an OS service like [gcore](https://www.man7.org/linux/man-pages/man1/gcore.1.html) for Linux?

cc @tommcdon, @elinor-fung

**Comment by jander-msft** [comment]
We are actually planning to move to using event pipe only for dump collection. The fact that it's not using it for Windows is a relic from long time ago when event pipe didn't support dump collection on Windows (I think in pre-5.0 timeframe) but was supported everywhere else.

**Comment by jander-msft** [comment]
We cannot do dumps directly from .NET Monitor given that it's likely to be running in a different process namespace in Kubernetes environments as a sidecar container.

**Comment by jander-msft** [comment]
As stated in https://github.com/dotnet/dotnet-monitor/issues/4534#issuecomment-1577381149, the .NET Monitor tool requires the use of the diagnostic channel to collect dumps due to the tool running in a different process namespace under the recommended configuration.
