### ISSUE TITLE
Not able to collect custom metrics 

### ISSUE THREAD

**Issue by jaya-rama** [dotnet/dotnet-monitor#475]
I deployed dotnet monitor as a side car  and I have written a custom metric using EventCounter in my dotnet application with Event Source name demo.RequestTime and added the below json file as a secret with name api-secret

{
    "Metrics": {
      "Providers": [
        {
          "ProviderName": "demo.RequestTime"
        }
      ]
    }
}

And below is my YAML file for deployment and I'm not getting custom metrics created using EventCounter when I access /metrics end point.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmonitorsample
  labels:
    app: dotnetmonitorsample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetmonitorsample
  template:
    metadata:
      labels:
        app: dotnetmonitorsample
    spec:
      volumes:
      - name: sharedtmp
        emptyDir: {}
      - name: api-secret
        secret:
          secretName: api-secret
      containers:
      - name: dotnetmonitorsample
        image: dd:v1
        volumeMounts:
          - name: sharedtmp
            mountPath: /tmp
      - name: dotnetmonitoragent
        image: mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.1
        ports:
          - containerPort: 52325
        args: ["--urls", "http://*:52323", "--metricUrls", "http://*:52325"]
        volumeMounts:
          - name: sharedtmp
            mountPath: /tmp
          - name: api-secret
            mountPath: /etc/dotnet-monitor

**Comment by jander-msft** [comment]
Are you certain that your custom event source provider has a name of `Microsoft-AspNetCore-Server-Kestrel`? That looks like a built-in event source provider.

**Comment by jaya-rama** [comment]
Sorry I copied wrong json file, I edited the json file now can you please see it once

**Comment by jander-msft** [comment]
Your JSON content needs to be mounted as a settings.json file under /etc/dotnet-monitor, otherwise dotnet-monitor will not be able to discover the settings.

**Comment by jaya-rama** [comment]
My JSON content is mounted as settings.json file under /etc/dotnet-monitor

I followed the below steps  to add custom metrics support can you see once and check if I miss anything

step 1: Created a custom metric using EventCounter with EventSource name demo.RequestTime 
step 2: Created a settings.json file with the below JSON content 
{
    "Metrics": {
      "Providers": [
        {
          "ProviderName": "demo.RequestTime"
        }
      ]
    }
}
step 3: created a secret using the command: Kubectl create secret generic api-secret --from file="C:\Users\jaya.reddy\Desktop\Demo\demo1\settings.json" 
step 4: Deployed the below YAML file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetmonitorsample
  labels:
    app: dotnetmonitorsample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetmonitorsample
  template:
    metadata:
      labels:
        app: dotnetmonitorsample
    spec:
      volumes:
      - name: sharedtmp
        emptyDir: {}
      - name: api-secret
        secret:
          secretName: api-secret
      containers:
      - name: dotnetmonitorsample
        image: dd:v1
        volumeMounts:
          - name: sharedtmp
            mountPath: /tmp
      - name: dotnetmonitoragent
        image: mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.1
        ports:
          - containerPort: 52325
        args: ["--urls", "http://*:52323", "--metricUrls", "http://*:52325"]
        volumeMounts:
          - name: sharedtmp
            mountPath: /tmp
          - name: api-secret
            mountPath: /etc/dotnet-monitor
step5: used the cmd to port-forward: kubectl port-forward pod/dotnetmonitorsample-b4b496977-5tkbx 7001:52323
step:6 accessed localhost:7001/metrics  and I don't see my custom metrics

**Comment by jander-msft** [comment]
You should check the status of your pod and make sure all of the containers are running. From my testing, it is likely your dotnet-monitor container keeps exiting. With your choice of args for the dotnet-monitor container `args: ["--urls", "http://:52323", "--metricUrls", "http://:52325"]` I'm seeing that the dotnet-monitor container exits. If I look at the logs on the container, it shows:

```
{"Timestamp":"2021-06-22T15:38:40.8803854Z","EventId":15,"LogLevel":"Error","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Unable to listen to http://:52323. Dotnet-monitor functionality will be limited.","Exception":"System.FormatException: Invalid url: \u0027http://:52323\u0027    at Microsoft.AspNetCore.Http.BindingAddress.Parse(String address)    at Microsoft.Diagnostics.Tools.Monitor.AddressListenResults.Listen(KestrelServerOptions options, String url) in /_/src/Tools/dotnet-monitor/AddressListenResults.cs:line 74","State":{"Message":"Unable to listen to http://:52323. Dotnet-monitor functionality will be limited.","url":"http://:52323","{OriginalFormat}":"Unable to listen to {url}. Dotnet-monitor functionality will be limited."},"Scopes":[]}
{"Timestamp":"2021-06-22T15:38:40.8854161Z","EventId":15,"LogLevel":"Error","Category":"Microsoft.Diagnostics.Tools.Monitor.Startup","Message":"Unable to listen to http://:52325. Dotnet-monitor functionality will be limited.","Exception":"System.FormatException: Invalid url: \u0027http://:52325\u0027    at Microsoft.AspNetCore.Http.BindingAddress.Parse(String address)    at Microsoft.Diagnostics.Tools.Monitor.AddressListenResults.Listen(KestrelServerOptions options, String url) in /_/src/Tools/dotnet-monitor/AddressListenResults.cs:line 74","State":{"Message":"Unable to listen to http://:52325. Dotnet-monitor functionality will be limited.","url":"http://:52325","{OriginalFormat}":"Unable to listen to {url}. Dotnet-monitor functionality will be limited."},"Scopes":[]}
{"Timestamp":"2021-06-22T15:38:40.9626451Z","EventId":6,"LogLevel":"Critical","Category":"Microsoft.AspNetCore.Hosting.Diagnostics","Message":"Application startup exception","Exception":"Microsoft.Diagnostics.Monitoring.MonitoringException: Unable to bind any urls.    at Microsoft.Diagnostics.Tools.Monitor.Startup.Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime, IWebHostEnvironment env, IAuthOptions options, AddressListenResults listenResults, ApiKeyAuthenticationOptionsObserver optionsObserver, ILogger\u00601 logger)    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.\u003C\u003Ec__DisplayClass4_0.\u003CBuild\u003Eb__0(IApplicationBuilder builder)    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.\u003C\u003Ec__DisplayClass13_0.\u003CUseStartup\u003Eb__2(IApplicationBuilder app)    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.\u003C\u003Ec__DisplayClass0_0.\u003CConfigure\u003Eg__MiddlewareFilterBuilder|0(IApplicationBuilder builder)    at Microsoft.AspNetCore.HostFilteringStartupFilter.\u003C\u003Ec__DisplayClass0_0.\u003CConfigure\u003Eb__0(IApplicationBuilder app)    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)","State":{"Message":"Application startup exception","{OriginalFormat}":"Application startup exception"},"Scopes":[]}
```

You need to specify a host for each of the URLs, e.g. `args: [ "--urls", "http://localhost:52323", "--metricUrls", "http://localhost:52325" ]` in order for the tool to run.

**Comment by jander-msft** [comment]
Once you get your container running and if you are still having issues, you can exec into the container to run `dotnet-monitor config show` to make sure that dotnet-monitor sees your configuration. Please provide that configuration with your next update if you are still having issues.

**Comment by jander-msft** [comment]
Separately, I would encourage you to update your image to Preview 5: `mcr.microsoft.com/dotnet/monitor:5.0.0-preview.5`. The Preview 1 image is now a year old and many enhancements and bug fixes have been made since then. If you do move to a newer image (Preview 4 or newer), be aware that authentication is being enforced (#27). Please read the [documentation](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/authentication.md) for more information.

**Comment by jander-msft** [comment]
I'm closing this issue because it's going stale and I believe the problem was that your container wasn't actually running. Feel free to reopen if you need more help specifically with this issue.
