### ISSUE TITLE
Repo doesn't include Dockerfile used to generate image hosted on MCR

### ISSUE THREAD

**Issue by webbsk** [dotnet/dotnet-monitor#483]
I haven't been able to find a Dockerfile in the repo that is used to generate mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview. This would be useful to do testing to make changes for containerized environments. Is it hosted somewhere else? 

I had a look with dive and all I see is the hash:
   5.6 MB  FROM d09376239d873ac 
   4.3 MB  apk add --no-cache         ca-certificates                 krb5-libs  
   77 MB  dotnet_version=3.1.16     && wget -O dotnet.tar.gz https://dotnetcli. 
   18 MB  aspnetcore_version=3.1.16     && wget -O aspnetcore.tar.gz https://do 
   0 B  #(nop) WORKDIR /app                                                   
   6.8 MB  #(nop) COPY dir:13b717f449f1a1dbffe1529fe1a08a719169cb302986d324defb4 
   90 kB  chmod 755 dotnet-monitor

**Comment by jander-msft** [comment]
The Dockerfile for dotnet-monitor is in the dotnet-docker repo here: https://github.com/dotnet/dotnet-docker/blob/main/src/monitor/5.0/alpine/amd64/Dockerfile
