### ISSUE TITLE
Generate process instance cookie for .NET Core 3.1 applications

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#49]
The concept of the runtime instance cookie was not introduced until .NET 5. However, there may be enough information for .NET Core 3.1 applications to generate a stable identifier. For example:
- Windows: Process ID + process start time encoded into a GUID
- Linux/MacOS: Process ID + diagnostic pipe disambiguator encoded into GUID

Using the process start time on Windows should be allowable because only the same user (or elevated user) can read/write to the pipe and the process must be in the same process namespace as the diagnostic process; the diagnostic pipe likely does not work across two Windows containers because the pipe must be served from the host machine whereas the diagnostic pipe in 3.1 is served from the same environment as the application (the container) and the diagnostic pipe is only implemented as named pipe on Windows.

**Comment by jander-msft** [comment]
cc: @josalem

**Comment by josalem** [comment]
If I'm understanding correctly, you want to build an out of process UID for a given runtime by concatenating pid+timestamp?  Process start time (either by checking the pipe or reading the disambiguator) should be a unique enough value for that in a given environment.  Is there a concern about calculating these for 3.1 runtime targets?

**Comment by jander-msft** [comment]
> If I'm understanding correctly, you want to build an out of process UID for a given runtime by concatenating pid+timestamp?

Correct.

> Process start time (either by checking the pipe or reading the disambiguator) should be a unique enough value for that in a given environment. Is there a concern about calculating these for 3.1 runtime targets?

I don't have too much of a concern about the stability of the calculation.

I'm laying out the reasoning why this should be able to work in all supported diagnostic pipe scenarios. For example, it would not work if we _could_ use the diagnostic pipe between two Windows containers because the dotnet-monitor container would not have the ability to inspect information about the process in the app container. My understanding is that this set up isn't possible for the diagnostic pipe because (1) it uses named pipes on Windows and (2) named pipes that are shared to Windows containers must served from the host machine. In this is the case, then it follows that:
- a .NET Core 3.1 app in a container cannot share its diagnostic pipe to another Windows container.
- Any process that dotnet-monitor can see on Windows is in the same process namespace as dotnet-monitor itself
- dotnet-monitor can use APIs to query about the target process information.

I think I have more concern about whether the dotnet-monitor process has the ability to look at the start time of any process it can discover via the diagnostic pipe existence (e.g. does it require elevation to look at process start time?), but that can be easily verified with some quick testing.
