### ISSUE TITLE
Diagnostic port connect mode may not work in Kubernetes

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#491]
Mounting the /tmp path between containers and using connect mode (the default mode) may not discover processes correctly. I validated with the customer that /tmp was mounted and that the event pipe socket from the application container was visible to dotnet-monitor. This target application is .NET 5; we were able to avoid the issue by using listen mode.

**Comment by shirhatti** [comment]
Was there anything interesting about the volume? Was it an emptyDir or something else?

**Comment by jander-msft** [comment]
It was an emptyDir if I recall correctly. I'm going to try to reproduce the issue myself and see what happens.
