### ISSUE TITLE
Suggested requests and limits in Kubernetes?

### ISSUE THREAD

**Issue by webbsk** [dotnet/dotnet-monitor#501]
### Documentation Request

I had heard from you that there is perf testing that you've already done on this. Can we please have those results posted in the documentation somewhere?

Also, are there suggested requests and limits that you were using for the dotnet-monitor container? That is, are there minimum requirements that you have identified?

**Comment by jander-msft** [comment]
I think @wiktork was taking a look at documenting them.

**Comment by jaya-rama** [comment]
any update on this?

**Comment by wiktork** [comment]
I will try to get this updated as soon as possible.
