### ISSUE TITLE
Wrong prometheus labels with npgsql 7.0 provider enabled

### ISSUE THREAD

**Issue by tierpod** [dotnet/dotnet-monitor#5094]
Hi,

### Description

We enabled Npgsql provider for dotnet-monitor some time ago (added `Npgsql` to /etc/dotnet-monitor/Metrics__Providers__0__ProviderName) to collect some npgsql metrics, for example `npgsql_connection_pools`

After upgrading ngpsql to version 7.0, we discovered that new metrics appeared in metrics output, and they looks broken:

```
npgsql_Idle_Connections__Host_example_local_Port_5432_Database_example_db_Username_example_user_Pooling_true__ 1691412078146
```

I assume, that it should be something like this:

```
npgsql_Idle_Connections{Host="example.local",Port="5432",Database="example_db",Username="example_user",Pooling="true"} 1691412078146
```

```bash
# dotnet-monitor --version
7.2.1+5607145aa39d3052d9bdbd08b8e0bb0596dcf935

# dotnet --list-sdks
7.0.105 [/usr/lib64/dotnet/sdk]
```

I found this [issue](https://github.com/npgsql/npgsql/issues/4157) and this [PR](https://github.com/npgsql/npgsql/commit/599523b54eef6bde2bf64d1adfd26dc676545a57) in npgsql project, that was included in npgsql 7.0.0.

Also, I found [this](https://github.com/dotnet/dotnet-monitor/blob/main/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/PrometheusDataModel.cs#L105C17-L105C17) comment in dotnet-monitor project

```
//TODO We don't have any labels in the current metrics implementation, but may need to add support for it
//for tags in the new dotnet metrics. Labels have some additional restrictions.
```

and maybe it relates to the problem.

I'm not sure whether this is a problem in dotnet-monitor project, or ngsqpl project, but maybe we can figure it out together.

Thank you.

**Comment by kkeirstead** [comment]
Hey, I just took a pass at this - from taking a quick look at the code, this behavior seems expected. Based on this [code](https://github.com/npgsql/npgsql/blob/main/src/Npgsql/NpgsqlEventSource.cs#L200) and some of the discussion in the issue you linked, it looks like they're trying to do something that's not inherently supported for EventCounter metrics by including tagging in the name. System Diagnostics Metrics allows for the use of [multi-dimensional metrics](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/metrics-instrumentation#multi-dimensional-metrics), which looks a lot like the example you specified of what you expected the output to look like. `Dotnet Monitor` treats parentheses as invalid characters (see [here](https://github.com/dotnet/dotnet-monitor/blob/main/src/Microsoft.Diagnostics.Monitoring.WebApi/Metrics/PrometheusDataModel.cs#L122)), which would explain the double `__` between `Connections` and `Host` - we don't have any special logic to look for parentheses in the counter's display name and parse the contents as tags. I'll plan to close out this issue, but feel free to reopen this thread if you think I may have overlooked something :)

**Comment by tierpod** [comment]
Thank you for answer. JFYI, it looks like System Diagnostics Metrics [will be implemented ](https://github.com/npgsql/npgsql/issues/5035#issuecomment-1644777383) in npgsql soon.
