### ISSUE TITLE
Unable to read Kestrel output in Prometheus due to dash character in event name

### ISSUE THREAD

**Issue by webbsk** [dotnet/dotnet-monitor#529]
### Description

Prometheus is unable to read the Kestrel output because of the dash being an illegal character.

This is what I am seeing when Prometheus attempts to read the Dotnet-Monitor metrics endpoint:
"invalid metric type "aspnetcore-server-kestrel_connections_per_second gauge"

This only started happening once I was able to successfully scrape the endpoint with Kestrel source enabled.

### Configuration

Only relevant configuration is probably that the Kestrel event provider is enabled.

### Regression?

Unknown.

### Other information

I'm going to see if I can use relabelling in the servicemonitor to workaround but the correct format should probably be outputted from Dotnet-Monitor (remove illegal characters from event names for Prometheus scraping).

**Comment by webbsk** [comment]
The formatting for the DotNet providers must snap to the Prometheus format in order to be scraped without errors: https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

**Comment by webbsk** [comment]
You may want to do the full checking and formatting (removing all illegal characters from the name like in the link in the above comment) but that may be beyond the scope of this bug.

**Comment by shirhatti** [comment]
The issue with our naive logic to drop `.` (and with your PR now `-`) from providers names is that they are no longer guaranteed to be unique. We may to escape the provider/counter names (I'm not a fan either🤮) before converting to snake case.

**Comment by jander-msft** [comment]
> The issue with our naive logic to drop `.` (and with your PR now `-`) from providers names is that they are no longer guaranteed to be unique.

I have the same concern as well.

> We may to escape the provider/counter names (I'm not a fan either🤮) before converting to snake case.

We might need to convert every non-alphanumeric character to an underscore according to what is allows by the Prometheus spec.

**Comment by webbsk** [comment]
Yes, I understand your concern about uniqueness but I think what I am focused on is this part from the Prometheus metrics names and label requirements: ` It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.` How you decide to implement that on your side is up to you, my PR is just a quick way (and following your existing convention) to deal with the problem that you can utilize if you choose.

**Comment by jander-msft** [comment]
Fixed by #531
