### ISSUE TITLE
AzureAd authentication does not work on .net 8 builds of v8.0.0-rc.1

### ISSUE THREAD

**Issue by schmittjoseph** [dotnet/dotnet-monitor#5373]
In .net 8 builds of `v8.0.0-rc.1` AzureAd authentication will not work. All requests will be rejected as unauthorized. I've confirmed the regression is fixed in `main`, so the next dotnet-monitor v8 release will have the fix.

Issue is caused by: https://github.com/AzureAD/microsoft-identity-web/issues/2420

**Comment by jander-msft** [comment]
This should be fixed in the 8.0 RC 2 release.
