### ISSUE TITLE
Add the ability to specify log level on a per-category basis

### ISSUE THREAD

**Issue by shirhatti** [dotnet/dotnet-monitor#54]
```
GET /logs HTTP/1.1
Host: localhost:52323
User-Agent: curl/7.54.0
Accept: application/x-ndjson
{
  "Default": "Information",
  "Microsoft": "Warning",
  "Microsoft.Hosting.Lifetime": "Information"
}
```

**Comment by jander-msft** [comment]
- Should this be a POST instead of a GET? According to https://tools.ietf.org/html/rfc2616#section-4.3, the request body of a GET should be ignored.
- I assume you meant to write "Accept: application/json" for the Accept header.

**Comment by shirhatti** [comment]
Yes to both your questions 😅
