### ISSUE TITLE
Enable authentication via AAD

### ISSUE THREAD

**Issue by webbsk** [dotnet/dotnet-monitor#551]
## Background and Motivation

In order to have secrets rotated on a regular basis, we often use AAD auth with bearer authentication so that we can use and rotate the certs associated to the AAD client app on a regular basis with no manual intervention. 

## Proposed Feature

Enable AAD auth as in: https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet (I realize this is for Azure Storage but the premise is the same).

## Usage Examples

In order to enable the secure access of the metrics and also dump and traces, a service can enable their Dotnet-Monitor installation to run with AAD auth to allow for secure access of the endpoint that offloads the identity and secret management to AAD.

**Comment by wiktork** [comment]
Related to https://github.com/dotnet/dotnet-monitor/pull/463

**Comment by kelltrick** [comment]
Follow up design needed

**Comment by jander-msft** [comment]
Support for AAD authentication has been made available in the 7.1 and 8.0 Preview 2 release earlier this month.

**Comment by jander-msft** [comment]
Please see documentation here: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/authentication.md#azure-active-directory-authentication
