### ISSUE TITLE
Use DefaultProcess__* instead of DotnetMonitor_DefaultProcess__* in Docker image

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#568]
There are two environment variables that are set in the dotnet-monitor [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/nightly/src/monitor/5.0/alpine/amd64/Dockerfile) for specifying the default process filter. Because these two environment variables start with `DotnetMonitor_`, any setting of the `DefaultProcess__`* environment variables in a container orchestration system (e.g. Kubernetes) will be ignored. All `DotnetMonitor_`* variables take precedence over the non-`DotnetMonitor_`* variables due to https://github.com/dotnet/dotnet-monitor/blob/e012be4a8791dfdae9a0c86cf81a6a0cb82c0acf/src/Tools/dotnet-monitor/DiagnosticsMonitorCommandHandler.cs#L163

## Proposal

Update the [Dockerfile](https://github.com/dotnet/dotnet-docker/blob/nightly/src/monitor/5.0/alpine/amd64/Dockerfile) with the following changes:

```diff
# Default Filter
- DotnetMonitor_DefaultProcess__Filters__0__Key=ProcessId \
- DotnetMonitor_DefaultProcess__Filters__0__Value=1 \
+ DefaultProcess__Filters__0__Key=ProcessId \
+ DefaultProcess__Filters__0__Value=1 \
```

cc @wiktork

**Comment by wiktork** [comment]
At least for k8, the environment variables specified in the deployment override those in the base image. Why could the user not just  use the prefix in the deployment?

**Comment by jander-msft** [comment]
> At least for k8, the environment variables specified in the deployment override those in the base image. Why could the user not just use the prefix in the deployment?

Of course, anyone can put the prefix in front if they know to do it. While the prefix is [documented](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#translating-configuration-between-providers), (1) it doesn't say anything about how prefixed variables will override the non-prefixed ones, and (2) there is no indication that using the `DotnetMonitor_DefaultProcess__`* is required for the Docker image in order to successfully set those values. In fact, there is no alternate way of setting `DefaultProcess__`* via any other mechanism (key-per-file, settings.json, environment variables) because `DotnetMonitor_`* environment variables override all other settings.

This is "lowering the barrier to success" type of fix.
