### ISSUE TITLE
Settings.json with environment variables

### ISSUE THREAD

**Issue by JeremyMcNeilrli** [dotnet/dotnet-monitor#5769]
It looks to be possible to set the settings.json path via environment variables but the document doesn't have details on this. Can you add this to the docs or let me know what the environment variable should be named?

https://github.com/dotnet/dotnet-monitor/blob/f83deaff5e7cf5686eef1df7a2da85b8b852320e/documentation/configuration/configuration-sources.md?plain=1#L17

**Comment by jander-msft** [comment]
> It looks to be possible to set the settings.json path via environment variables

The location of the `settings.json` file is not configurable via environment variables.

The `settings.json` file is implicitly found at the paths specified at https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/configuration-sources.md?plain=1#L9. It can also be implicitly loaded from the `C:\ProgramData\dotnet-monitor` directory (on Windows) or the `/etc/dotnet-monitor` directory (on non-Windows); I will update the docs to reflect this information.

You can also specify a path to a `settings.json` file via the `--configuration-file-path` command line switch: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/configuration-sources.md?plain=1#L18

**Comment by JeremyMcNeilrli** [comment]
bummer I was really hoping to use the environment variable. thanks for the clarification.
