### ISSUE TITLE
Can we get memory dump and CPU trace automatically stores to S3 buckets when certain value of memory and CPU crossed

### ISSUE THREAD

**Issue by jaya-rama** [dotnet/dotnet-monitor#584]
Hi,

How can I get memory dump and cpu trace for a pod when the memory and cpu usage crosses some x value and stores directly in S3 buckets so that I can have access to the dump and trace when the pod gets terminated due to high memory and cpu usage. can we achieve this? if so how? 

summary: needs dotnet monitor to trigger /dump and /trace endpoints when the cpu and memory usage is above x%  and sends the data to S3 buckets or send data through mail

                                       OR 

store dump and trace data in S3 at regular intervals 

Environment: Kubernetes environment and dotnet monitor is integrated as side car for a pod

**Comment by shirhatti** [comment]
The recent work to [refactor egress configuration](https://github.com/dotnet/dotnet-monitor/pull/515) should make it possible for you to implement your own egress provider and read in configuration. Extensibility of dotnet-monitor is one of our core design tenets, even if we aren't the ones building the extensibility. To that end, we'd be happy to make additional changes to dotnet-monitor to make this possible if you run into any road blocks in attempting this.

Unfortunately, we do not have the resources to work on this at this moment in time. We may reconsider this at a later date, but it is not planned in the near future.

**Comment by maciejsobocinski** [comment]
If it helps I have done this by chaining gcdump action to Execute action which passes the egress path to a shell script that uploads the dump to s3

**Comment by jander-msft** [comment]
This should now be possible "natively" using a combination of [collection rules](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/collection-rule-configuration.md) and the [S3 egress provider](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration/egress-configuration.md#80-s3-storage-egress-provider) starting with .NET Monitor 8.0 Preview 1.
