### ISSUE TITLE
Experimenting in MAC

### ISSUE THREAD

**Issue by birojnayak** [dotnet/dotnet-monitor#6271]
### Description

1. Ran a simple Helloworld app in MAC.
2. Ran ``` dotnet-monitor collect --no-auth  --configuration-file-path settings.json```
3. Did curl with http://localhost:52325/processes, didn't get any response. Below is the result and ```settings.json```, I have copied to the configuration section.

```
biroj@88665a0182c9 dotnet-monitor % dotnet-monitor --version
8.0.1+01acd6a928a79a306f77d67f456b1a75745f360d
biroj@88665a0182c9 dotnet-monitor % curl http://localhost:52325/processes
biroj@88665a0182c9 dotnet-monitor % curl http://localhost:52325/processes
biroj@88665a0182c9 dotnet-monitor % ps -elf|grep "dotnet"                
  505 84574 57916     4006   0  46  0 34123300    588 -      R+                  0 ttys004    0:00.00 grep dotnet      11:10PM
  505 78287  3537     4046   0  33  0 36963664  32748 -      S+                  0 ttys007    0:05.49 dotnet run       10:10PM
  505 84190  8408     4046   0  33  0 36956600  68036 -      S+                  0 ttys009    0:02.00 dotnet-monitor c 11:06PM
biroj@88665a0182c9 dotnet-monitor % 
```

### Configuration

```json
{
  "$schema": "https://aka.ms/dotnet-monitor-schema",
  "Egress": {
    "FileSystem": {
        "monitorFile": {
            "directoryPath": "/tmp/dotnet-monitor"
        }
    }
}
}
```
### Regression?
Don't know...

**Comment by wiktork** [comment]
> Did curl with http://localhost:52325/processes
You'll want to use http://localhost:52323/processes. 52325 only serves metrics by default.

**Comment by jander-msft** [comment]
I'm going to close this issue since a solution as provided and we haven't heard of any feedback for over a month. Please feel free to reopen if you feel that this issue hasn't be resolved.
