### ISSUE TITLE
Register collection rule triggers via service registration

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#630]
Trigger implementations shall be registered via service registration when dotnet-monitor is started. A trigger registration will describe (1) its name (described as `Type` in configuration), (2) the implementation type of the trigger interface, and (3) optionally, the settings type used to bind options from configuration. An example of this may look like:

`services.AddCollectionRuleTrigger<CounterTriggerFactory, CounterTriggerOptions>("CounterTrigger");`

or

`services.AddCollectionRuleTrigger<StartupTriggerFactory>("StartupTrigger");`

for triggers that do not take options.

**Comment by shirhatti** [comment]
Similar to what we did for egress providers:

https://github.com/dotnet/dotnet-monitor/blob/847374b73b4197885c8b0ab926e1047519cd35f8/src/Tools/dotnet-monitor/ServiceCollectionExtensions.cs#L59-L60
