### ISSUE TITLE
Investigate impact of long running DiagnosticSourceEventSource usage

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#647]
Several of the ASP.NET triggers will like use the `Microsoft-Diagnostics-DiagnosticSource` event provider to collect ASP.NET events such as `Microsoft.AspNetCore/Microsoft.AspNetCore.Hosting.HttpRequestIn.Start` and `Microsoft.AspNetCore/Microsoft.AspNetCore.Hosting.HttpRequestIn.Stop`. Investigate the impact (memory, cpu) of using this provider for long spans of time (entire target process lifetime) for applications that are under high load (many requests).

**Comment by wiktork** [comment]
I was not able to observe any significant impact from a asp.net trigger prototype. Methodology:
- Bombardier was used to load test the website
- A trigger prototype was written against asp.net provider. See https://github.com/wiktork/diagnostics/tree/dev/wiktork/triggerProto and https://github.com/wiktork/dotnet-monitor/tree/dev/wiktork%2FaspnetTriggerTesting
- The trigger action was to simply log the event (using ILogger in the agent)

No significant RPS difference was observed when running with the trigger or without. 
No significant impact on cpu/memory usage was observed.

**Comment by wiktork** [comment]
Closing this out, so far the asp.net triggers are meeting perf goals under load.
