### ISSUE TITLE
Difficulty Configuring dotnet-monitor for Continuous Log Collection

### ISSUE THREAD

**Issue by jgador** [dotnet/dotnet-monitor#6565]
**dotnet-monitor version: 8.0.1**

I am currently facing challenges in configuring dotnet-monitor to achieve continuous log collection and egress into local folder.

**appsettings.json**
``` json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Information",
      "Microsoft.Diagnostics": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "Console": {
      "FormatterName": "simple",
      "FormatterOptions": {
        "IncludeScopes": true,
        "TimestampFormat": "HH:mm:ss "
      }
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft": "Information",
        "Microsoft.Diagnostics": "Information",
        "Microsoft.Hosting.Lifetime": "Information"
      }
    }
  },
  "DefaultProcess": {
    "Filters": [
      {
        "ProcessName": "Logs.Consumer"
      }
    ],
    "Trigger": {
      "Type": "Startup"
    },
    "Actions": {
      "Type": "CollectLogs",
      "Settings": {
        "Egress": "artifacts"
      }
    }
  },
  "DiagnosticPort": {
    "ConnectionMode": "Listen",
    "EndpointName": "\\\\.\\pipe\\dotnet-monitor-pipe"
  },
  "Egress": {
    "FileSystem": {
      "artifacts": {
        "directoryPath": "C:\\Users\\jesse\\OneDrive\\Desktop\\temp\\dotnet-monitor-egress"
      }
    }
  },
  "AllowedHosts": "*"
}
```

Initially, my objective is to establish successful egress to a local folder. Once this functionality is operational, I plan to explore integrating dotnet-monitor with Azure Event Hub for more extensive logging capabilities.

**Comment by jander-msft** [comment]
This problem is that the configuration is not correctly specified to collect logs. The trigger and actions must be specified as a collection rule, not as part of the default process configuration.

```diff
  "DefaultProcess": {
    "Filters": [
      {
        "ProcessName": "Logs.Consumer"
      }
-   ],
+   ]
-   "Trigger": {
-     "Type": "Startup"
-   },
-   "Actions": {
-     "Type": "CollectLogs",
-     "Settings": {
-       "Egress": "artifacts"
-     }
-   }
  },
+ "CollectionRules": {
+   "LogsRule": {
+     "Trigger": {
+       "Type": "Startup"
+     },
+     "Actions": [{
+       "Type": "CollectLogs",
+       "Settings": {
+         "Egress": "artifacts"
+       }
+     }]
+   }
+ },
```

There is a JSON schema document that describes the expected form of the JSON configuration if you are using an editor that supports JSON schema: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/schema.json#L30

**Comment by jgador** [comment]
Perfect, that solved my problem. I'm new to the dotnet-monitor and I gave it a try since I worked at Stackify/Netreo which is a logging solution SaaS company. I hope to be able to contribute egress to Azure Event Hub. I'm closing this issue.
