### ISSUE TITLE
Getting Started documentation is missing

### ISSUE THREAD

**Issue by darraghjones** [dotnet/dotnet-monitor#661]
### Documentation Request

The Getting Started links on this page simply point to # : https://github.com/dotnet/dotnet-monitor/tree/main/documentation

I'm particular curious how to run dotnet monitor locally.

https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor/
https://devblogs.microsoft.com/dotnet/whats-new-in-dotnet-monitor/

**Comment by jander-msft** [comment]
"How" `dotnet monitor` is run locally is covered by the first blog post you linked to: https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor/#local-machine

That shows how to get the latest nightly build. If you want the latest preview release, look at the setup documentation: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/setup.md

[configuration.md](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md) explains how to configure it and what can be configured. [authentication.md](https://github.com/dotnet/dotnet-monitor/blob/main/documentation/authentication.md) explains how to authenticate with the HTTP server.

If you have more specific questions beyond "how to run dotnet monitor locally", please feel free to ask.

**Comment by darraghjones** [comment]
I appreciate your response. However, if this is where people should be looking for documenation on how to run dotnet monitor locally, then why not update the anchor tag under "Getting Started -> Running on a local machine" to link to these places, rather than linking to nowhere? 

Otherwise it just seems like a bug in the documentation which is why I raised this issue in the first place.

**Comment by jander-msft** [comment]
Point taken; I've logged a new issue specifically about filling out the documentation.
