### ISSUE TITLE
Add /info endpoint

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#76]
This should provide dotnet-monitor version, and possibly configuration (w/o PII)
- Listening mode (+ port)
- other configuration knobs

**Comment by jander-msft** [comment]
For Preview 6, just add "version" property as top-level on JSON object response.

```json
{
  "version": "5.0.0-preview.5.21302.5+a99ec90eb220fa3b57f089677d8d1e85d48fb3a8"
}
```

**Comment by kelltrick** [comment]
See #546 for full details.
