### ISSUE TITLE
dotnet tool install fails to install "latest" dotnet-monitor

### ISSUE THREAD

**Issue by xSAVIKx** [dotnet/dotnet-monitor#7674]
### Description

`dotnet tool install --tool-path /tools dotnet-monitor` fails to install in latest [dotnet/sdk:8.0](mcr.microsoft.com/dotnet/sdk:8.0@sha256:f91f9181d68b5ed2c8dea199dbbd2f6d172e60bdc43f8a67878b1ad140cf8d6b) container with:
```
Tool 'dotnet-monitor' failed to update due to the following:
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'dotnet-monitor' failed to install. Contact the tool author for assistance.
```

it looks like only v9.0.0 can't be installed.

### Configuration

Running inside latest .net SDK official container: mcr.microsoft.com/dotnet/sdk:8.0@sha256:f91f9181d68b5ed2c8dea199dbbd2f6d172e60bdc43f8a67878b1ad140cf8d6b

Also tried with `sdk:8.0-noble` - same result as this is not env-specific IMO.

### Other information

it works fine if I specify version explicitly:
```
dotnet tool install --tool-path /tools --version 8.0.5 dotnet-monitor
```
or with the latest version:
```
dotnet tool install --tool-path /tools --version 8.0.6 dotnet-monitor
```

**Comment by jander-msft** [comment]
.NET Monitor 9 tool package is only installable in an environment that contains a .NET 9 SDK. If you are unable to change the .NET SDK container to .NET 9, then you'll only be able to install .NET Monitor 8. You can get the latest installation of .NET Monitor 8 by running

```
dotnet tool install -g dotnet-monitor --version 8.*
```

**Comment by xSAVIKx** [comment]
Yeah, that's what I did already, but it's kinda odd to not being able to install it without explicitly specifying the version.

**Comment by jander-msft** [comment]
In general, .NET tools can only be installed via matching SDKs where the runtime version of the tool has to match the SDK version. Since .NET Monitor 9 only has a target framework of `net9.0`, it will require the .NET 9 SDK to install it. Similarly, .NET Monitor 8 only has a target framework of `net8.0`, it will require the .NET 8 SDK to install it.

I can go update the docs to reflect this requirement.

**Comment by jander-msft** [comment]
We have no plans for allowing .NET Monitor 9 to run on versions lower than .NET 9.

Since there is a solution to the reported problem, and there is no work to be done on the tool itself, I will be closing this issue as not planned.
