### ISSUE TITLE
Unable to get dump file after accessing /dump 

### ISSUE THREAD

**Issue by jaya-rama** [dotnet/dotnet-monitor#770]
Hi 

I'm not able to get dump file after accessing /dump endpoint, but /trace, /gcdump is working fine

I'm using dotnet monitor as sidecar for a pod in kubernetes(EKS) and image name is mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.1

Below are some exceptions

![image](https://user-images.githubusercontent.com/60612892/130915208-b152e2ac-7f68-4100-809c-8bd83ccb26d8.png)
![image](https://user-images.githubusercontent.com/60612892/130915280-f9f9751e-15af-4757-bff5-2aa4cd2c94aa.png)

**Comment by jaya-rama** [comment]
Is there any complete working example in kubernetes ?

**Comment by jander-msft** [comment]
I forgot to mention this a while ago, but there is now a complete Kubernetes example at https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md
