### ISSUE TITLE
Web API Review

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#8]

**Comment by wiktork** [comment]
Feedback from api review: 

- Consider whether process filter should be a query vs a path segement
- Unify /env with the remaining  apis
- Return different result codes for different media types.
- Consider json sequence instead of application/ndjson
- Consider Post redirect get during expensive GET operations

**Comment by jander-msft** [comment]
Initial review was completed, resulting with the following issues: #66, #67, #68, #69, #70, #71, #72, #73, #75, #76
