### ISSUE TITLE
Clerify on how to run dotnet monitor locally.

### ISSUE THREAD

**Issue by AchoArnold** [dotnet/dotnet-monitor#89]
### Documentation Request

How to use dotnet monitor locally

### Previous documentation

[The documentation](https://devblogs.microsoft.com/dotnet/introducing-dotnet-monitor/) says I can run dotnet monitor with the command  `dotnet monitor collect`

But when I run this command locally, I get the error 

`Process id 0, does not support event pipe`

I have the web app running with `dotnet run` command 

Is there something extra we have to do to run the monitor locally?

**Comment by jander-msft** [comment]
Can you run `dotnet monitor --version` and let us know what version it is reporting?

If you acquired dotnet-monitor recently, you should have a version that looks like `5.0.0-preview.4.*`

Additionally, you can try running dotnet-monitor with `dotnet-monitor collect` (note the hyphen between 'dotnet' and 'monitor').

**Comment by AchoArnold** [comment]
`dotnet monitor --version`

3.1.135903+0ed39ffbc1d1520cacab8e61383a170b0f993941

`dotnet-monitor collect`

Process id 0, does not support event pipe


![Screenshot 2021-03-18 214453](https://user-images.githubusercontent.com/4196457/111687694-dd6f6080-882a-11eb-9215-83f25316b140.png)

**Comment by jander-msft** [comment]
Please continue to use the 5.0.* versions. The 3.* versions were mistakenly produced; I'll see if I can get them delisted or removed.

Regarding the error that you are seeing with the binding failure, that exception is typically thrown when the port is already in use. You can try to figure out what is using it and stop that process or you can have dotnet-monitor bind to a different port e.g. `dotnet monitor collect --urls https://localhost:<port>`

**Comment by AchoArnold** [comment]
Okay so I restarted my computer and it now appears to work. I can start the monitor with the `dotnet-monitor collect` command but when I attempt to do a request to the `/processes` endpoint, I get this error from the logs
 
 ```
 22:10:26 info: Microsoft.Diagnostics.Tools.Monitor.ApiKeyAuthenticationHandler[12]
      => ConnectionId:0HM7A97FGLERK => RequestPath:/processes RequestId:0HM7A97FGLERK:00000001, SpanId:|de110772-4005d733bb8d76fa., TraceId:de110772-4005d733bb8d76fa, ParentId:
      AuthenticationScheme: MonitorApiKey was challenged.
```

**Comment by jander-msft** [comment]
Please refer to the pinned issue regarding authentication: https://github.com/dotnet/dotnet-monitor/issues/27

**Comment by AchoArnold** [comment]
Thanks. I also did try to visit the `/metrics` endpoint which doesn't require authentication and it returns a `200` status code with no response.

![Screenshot 2021-03-18 222013](https://user-images.githubusercontent.com/4196457/111692466-bff0c580-882f-11eb-8adc-c8553a694c2f.png)

**Comment by AchoArnold** [comment]
Ahh, I did the authentication steps and now it works.

**Comment by jander-msft** [comment]
@AchoArnold, I believe the questions in this issue have been answered. If you have additional problems, please feel free to reopen or create new issues.
