### ISSUE TITLE
dotnet-monitor: Allow disabling endpoints

### ISSUE THREAD

**Issue by aelij** [dotnet/dotnet-monitor#9]
## Background and Motivation

Some of the information exposed by dotnet-monitor is highly sensitive, such as memory dumps. So we'd like the option to disable them.

## Proposed Feature

Command line arguments to enable/disable each endpoint.

## Usage Examples

```
dotnet-monitor --enable-dump false
```

**Comment by jander-msft** [comment]
.NET Monitor requires authentication to access the HTTP API surface which prevents access to the sensitive information unless the user is authenticated. The only authentication option in the current versions is API key, however Azure Active Directory is currently being implemented.
