### ISSUE TITLE
Running the source code from visualstudio

### ISSUE THREAD

**Issue by Saipavan018** [dotnet/dotnet-monitor#921]
Hi I am try to run the source code from visualstudio but I am facing on issue like
![IMG_20210928_201716_760](https://user-images.githubusercontent.com/87936491/135112899-be8b3c1e-801e-4e26-9fc2-71c910a7ebae.jpg)

Can u help me on this issue....
What I have missed to add after downloaded the code  to run the code from visualstudio...

 Pls help me @jander-msft @radical @bratsche @shanselman @AArnott @duncanmak @hoyosjs @kelltrick @marisayou @anurse @dotnet-bot 
@shirhatti

**Comment by hoyosjs** [comment]
Hey @Saipavan018. To run it in debug mode - which seems to be what you want - you can open `dotnet-monitor.sln` in the root of the repo, right click the project `dotnet-monitor.csproj` in the solution explorer, select properties. In the window that opens, select the debug tab and add the parameters needed (collect in this case). Then you can set breakpoints and hit the endpoints on localhost as needed.

**Comment by Saipavan018** [comment]
@hoyosjs  yeah solved tq so much and it is not supporting .net framework any feature implementation for monitoring .net framework also

**Comment by AArnott** [comment]
@Saipavan018 Please do not @ mention a bunch of random folks. Many of these probably don't even manage this repo (I certainly don't). Let the triage team do its work.
